/*
Eduframe - API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package eduframe

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ProgramEnrollment type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProgramEnrollment{}

// ProgramEnrollment struct for ProgramEnrollment
type ProgramEnrollment struct {
	// Unique identifier of the enrollment
	Id int32 `json:"id"`
	// The identifier of the associated student
	StudentId int32 `json:"student_id"`
	// The identifier of the associated edition
	EditionId int32 `json:"edition_id"`
	// The identifier of the associated personal program
	PersonalProgramId int32 `json:"personal_program_id"`
	// An array of integers representing unique identifier values associated with labels. 
	LabelIds []int32 `json:"label_ids"`
	// The identifier of the associated order
	OrderId NullableInt32 `json:"order_id"`
	// The state of the enrollment
	State string `json:"state"`
	GraduationState GraduationState `json:"graduation_state"`
	// The graduation date of the enrollment
	GraduationDate NullableString `json:"graduation_date"`
}

type _ProgramEnrollment ProgramEnrollment

// NewProgramEnrollment instantiates a new ProgramEnrollment object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProgramEnrollment(id int32, studentId int32, editionId int32, personalProgramId int32, labelIds []int32, orderId NullableInt32, state string, graduationState GraduationState, graduationDate NullableString) *ProgramEnrollment {
	this := ProgramEnrollment{}
	this.Id = id
	this.StudentId = studentId
	this.EditionId = editionId
	this.PersonalProgramId = personalProgramId
	this.LabelIds = labelIds
	this.OrderId = orderId
	this.State = state
	this.GraduationState = graduationState
	this.GraduationDate = graduationDate
	return &this
}

// NewProgramEnrollmentWithDefaults instantiates a new ProgramEnrollment object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProgramEnrollmentWithDefaults() *ProgramEnrollment {
	this := ProgramEnrollment{}
	return &this
}

// GetId returns the Id field value
func (o *ProgramEnrollment) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ProgramEnrollment) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ProgramEnrollment) SetId(v int32) {
	o.Id = v
}

// GetStudentId returns the StudentId field value
func (o *ProgramEnrollment) GetStudentId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.StudentId
}

// GetStudentIdOk returns a tuple with the StudentId field value
// and a boolean to check if the value has been set.
func (o *ProgramEnrollment) GetStudentIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StudentId, true
}

// SetStudentId sets field value
func (o *ProgramEnrollment) SetStudentId(v int32) {
	o.StudentId = v
}

// GetEditionId returns the EditionId field value
func (o *ProgramEnrollment) GetEditionId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.EditionId
}

// GetEditionIdOk returns a tuple with the EditionId field value
// and a boolean to check if the value has been set.
func (o *ProgramEnrollment) GetEditionIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EditionId, true
}

// SetEditionId sets field value
func (o *ProgramEnrollment) SetEditionId(v int32) {
	o.EditionId = v
}

// GetPersonalProgramId returns the PersonalProgramId field value
func (o *ProgramEnrollment) GetPersonalProgramId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.PersonalProgramId
}

// GetPersonalProgramIdOk returns a tuple with the PersonalProgramId field value
// and a boolean to check if the value has been set.
func (o *ProgramEnrollment) GetPersonalProgramIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PersonalProgramId, true
}

// SetPersonalProgramId sets field value
func (o *ProgramEnrollment) SetPersonalProgramId(v int32) {
	o.PersonalProgramId = v
}

// GetLabelIds returns the LabelIds field value
func (o *ProgramEnrollment) GetLabelIds() []int32 {
	if o == nil {
		var ret []int32
		return ret
	}

	return o.LabelIds
}

// GetLabelIdsOk returns a tuple with the LabelIds field value
// and a boolean to check if the value has been set.
func (o *ProgramEnrollment) GetLabelIdsOk() ([]int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.LabelIds, true
}

// SetLabelIds sets field value
func (o *ProgramEnrollment) SetLabelIds(v []int32) {
	o.LabelIds = v
}

// GetOrderId returns the OrderId field value
// If the value is explicit nil, the zero value for int32 will be returned
func (o *ProgramEnrollment) GetOrderId() int32 {
	if o == nil || o.OrderId.Get() == nil {
		var ret int32
		return ret
	}

	return *o.OrderId.Get()
}

// GetOrderIdOk returns a tuple with the OrderId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ProgramEnrollment) GetOrderIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.OrderId.Get(), o.OrderId.IsSet()
}

// SetOrderId sets field value
func (o *ProgramEnrollment) SetOrderId(v int32) {
	o.OrderId.Set(&v)
}

// GetState returns the State field value
func (o *ProgramEnrollment) GetState() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.State
}

// GetStateOk returns a tuple with the State field value
// and a boolean to check if the value has been set.
func (o *ProgramEnrollment) GetStateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.State, true
}

// SetState sets field value
func (o *ProgramEnrollment) SetState(v string) {
	o.State = v
}

// GetGraduationState returns the GraduationState field value
func (o *ProgramEnrollment) GetGraduationState() GraduationState {
	if o == nil {
		var ret GraduationState
		return ret
	}

	return o.GraduationState
}

// GetGraduationStateOk returns a tuple with the GraduationState field value
// and a boolean to check if the value has been set.
func (o *ProgramEnrollment) GetGraduationStateOk() (*GraduationState, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GraduationState, true
}

// SetGraduationState sets field value
func (o *ProgramEnrollment) SetGraduationState(v GraduationState) {
	o.GraduationState = v
}

// GetGraduationDate returns the GraduationDate field value
// If the value is explicit nil, the zero value for string will be returned
func (o *ProgramEnrollment) GetGraduationDate() string {
	if o == nil || o.GraduationDate.Get() == nil {
		var ret string
		return ret
	}

	return *o.GraduationDate.Get()
}

// GetGraduationDateOk returns a tuple with the GraduationDate field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ProgramEnrollment) GetGraduationDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.GraduationDate.Get(), o.GraduationDate.IsSet()
}

// SetGraduationDate sets field value
func (o *ProgramEnrollment) SetGraduationDate(v string) {
	o.GraduationDate.Set(&v)
}

func (o ProgramEnrollment) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProgramEnrollment) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["student_id"] = o.StudentId
	toSerialize["edition_id"] = o.EditionId
	toSerialize["personal_program_id"] = o.PersonalProgramId
	toSerialize["label_ids"] = o.LabelIds
	toSerialize["order_id"] = o.OrderId.Get()
	toSerialize["state"] = o.State
	toSerialize["graduation_state"] = o.GraduationState
	toSerialize["graduation_date"] = o.GraduationDate.Get()
	return toSerialize, nil
}

func (o *ProgramEnrollment) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"student_id",
		"edition_id",
		"personal_program_id",
		"label_ids",
		"order_id",
		"state",
		"graduation_state",
		"graduation_date",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varProgramEnrollment := _ProgramEnrollment{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varProgramEnrollment)

	if err != nil {
		return err
	}

	*o = ProgramEnrollment(varProgramEnrollment)

	return err
}

type NullableProgramEnrollment struct {
	value *ProgramEnrollment
	isSet bool
}

func (v NullableProgramEnrollment) Get() *ProgramEnrollment {
	return v.value
}

func (v *NullableProgramEnrollment) Set(val *ProgramEnrollment) {
	v.value = val
	v.isSet = true
}

func (v NullableProgramEnrollment) IsSet() bool {
	return v.isSet
}

func (v *NullableProgramEnrollment) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProgramEnrollment(val *ProgramEnrollment) *NullableProgramEnrollment {
	return &NullableProgramEnrollment{value: val, isSet: true}
}

func (v NullableProgramEnrollment) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProgramEnrollment) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


