/*
Eduframe - API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package eduframe

import (
	"encoding/json"
	"fmt"
)

// checks if the PlannedCoursePayload type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PlannedCoursePayload{}

// PlannedCoursePayload struct for PlannedCoursePayload
type PlannedCoursePayload struct {
	// Boolean if is published on the website.
	IsPublished *bool `json:"is_published,omitempty"`
	// Unique identifier of the course.
	CourseId int32 `json:"course_id"`
	// The type of the course.
	Type string `json:"type"`
	// Date at which the planned course starts. Only needed for fixed planned courses.
	StartDate *string `json:"start_date,omitempty"`
	// Date at which the planned course ends. Only needed for fixed planned courses.
	EndDate NullableString `json:"end_date,omitempty"`
	// A number representing the minimum number of participants that can enroll for the planned course.
	MinParticipants NullableInt32 `json:"min_participants,omitempty"`
	// A number representing the maximum number of participants that can enroll for the planned course.
	MaxParticipants NullableInt32 `json:"max_participants,omitempty"`
	// The cost schema that the payment will follow for the specified course.
	CostScheme *string `json:"cost_scheme,omitempty"`
	// The price to be paid for this planned course. Required if cost_scheme is student (default value) or order.
	Cost NullableFloat32 `json:"cost"`
	// Unique identifier of the course variant.
	CourseVariantId NullableInt32 `json:"course_variant_id,omitempty"`
	// Unique identifier of the course location.
	CourseLocationId NullableInt32 `json:"course_location_id,omitempty"`
	// The period of time of the planned course in days. Only needed for flexible planned courses.
	Duration *float32 `json:"duration,omitempty"`
	// The ids of the teachers in the course
	TeacherIds []int32 `json:"teacher_ids,omitempty"`
	// The custom properties of the planned course.
	Custom map[string]interface{} `json:"custom,omitempty"`
	// Custom associations are a way to link custom records to a program. ![Custom Objects](https://img.shields.io/badge/Feature-Custom_objects-1d8127) 
	CustomAssociations []CustomAssociationsRecordsPayload `json:"custom_associations,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _PlannedCoursePayload PlannedCoursePayload

// NewPlannedCoursePayload instantiates a new PlannedCoursePayload object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPlannedCoursePayload(courseId int32, type_ string, cost NullableFloat32) *PlannedCoursePayload {
	this := PlannedCoursePayload{}
	this.CourseId = courseId
	this.Type = type_
	this.Cost = cost
	return &this
}

// NewPlannedCoursePayloadWithDefaults instantiates a new PlannedCoursePayload object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPlannedCoursePayloadWithDefaults() *PlannedCoursePayload {
	this := PlannedCoursePayload{}
	return &this
}

// GetIsPublished returns the IsPublished field value if set, zero value otherwise.
func (o *PlannedCoursePayload) GetIsPublished() bool {
	if o == nil || IsNil(o.IsPublished) {
		var ret bool
		return ret
	}
	return *o.IsPublished
}

// GetIsPublishedOk returns a tuple with the IsPublished field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlannedCoursePayload) GetIsPublishedOk() (*bool, bool) {
	if o == nil || IsNil(o.IsPublished) {
		return nil, false
	}
	return o.IsPublished, true
}

// HasIsPublished returns a boolean if a field has been set.
func (o *PlannedCoursePayload) HasIsPublished() bool {
	if o != nil && !IsNil(o.IsPublished) {
		return true
	}

	return false
}

// SetIsPublished gets a reference to the given bool and assigns it to the IsPublished field.
func (o *PlannedCoursePayload) SetIsPublished(v bool) {
	o.IsPublished = &v
}

// GetCourseId returns the CourseId field value
func (o *PlannedCoursePayload) GetCourseId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.CourseId
}

// GetCourseIdOk returns a tuple with the CourseId field value
// and a boolean to check if the value has been set.
func (o *PlannedCoursePayload) GetCourseIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CourseId, true
}

// SetCourseId sets field value
func (o *PlannedCoursePayload) SetCourseId(v int32) {
	o.CourseId = v
}

// GetType returns the Type field value
func (o *PlannedCoursePayload) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *PlannedCoursePayload) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *PlannedCoursePayload) SetType(v string) {
	o.Type = v
}

// GetStartDate returns the StartDate field value if set, zero value otherwise.
func (o *PlannedCoursePayload) GetStartDate() string {
	if o == nil || IsNil(o.StartDate) {
		var ret string
		return ret
	}
	return *o.StartDate
}

// GetStartDateOk returns a tuple with the StartDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlannedCoursePayload) GetStartDateOk() (*string, bool) {
	if o == nil || IsNil(o.StartDate) {
		return nil, false
	}
	return o.StartDate, true
}

// HasStartDate returns a boolean if a field has been set.
func (o *PlannedCoursePayload) HasStartDate() bool {
	if o != nil && !IsNil(o.StartDate) {
		return true
	}

	return false
}

// SetStartDate gets a reference to the given string and assigns it to the StartDate field.
func (o *PlannedCoursePayload) SetStartDate(v string) {
	o.StartDate = &v
}

// GetEndDate returns the EndDate field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PlannedCoursePayload) GetEndDate() string {
	if o == nil || IsNil(o.EndDate.Get()) {
		var ret string
		return ret
	}
	return *o.EndDate.Get()
}

// GetEndDateOk returns a tuple with the EndDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PlannedCoursePayload) GetEndDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.EndDate.Get(), o.EndDate.IsSet()
}

// HasEndDate returns a boolean if a field has been set.
func (o *PlannedCoursePayload) HasEndDate() bool {
	if o != nil && o.EndDate.IsSet() {
		return true
	}

	return false
}

// SetEndDate gets a reference to the given NullableString and assigns it to the EndDate field.
func (o *PlannedCoursePayload) SetEndDate(v string) {
	o.EndDate.Set(&v)
}
// SetEndDateNil sets the value for EndDate to be an explicit nil
func (o *PlannedCoursePayload) SetEndDateNil() {
	o.EndDate.Set(nil)
}

// UnsetEndDate ensures that no value is present for EndDate, not even an explicit nil
func (o *PlannedCoursePayload) UnsetEndDate() {
	o.EndDate.Unset()
}

// GetMinParticipants returns the MinParticipants field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PlannedCoursePayload) GetMinParticipants() int32 {
	if o == nil || IsNil(o.MinParticipants.Get()) {
		var ret int32
		return ret
	}
	return *o.MinParticipants.Get()
}

// GetMinParticipantsOk returns a tuple with the MinParticipants field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PlannedCoursePayload) GetMinParticipantsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.MinParticipants.Get(), o.MinParticipants.IsSet()
}

// HasMinParticipants returns a boolean if a field has been set.
func (o *PlannedCoursePayload) HasMinParticipants() bool {
	if o != nil && o.MinParticipants.IsSet() {
		return true
	}

	return false
}

// SetMinParticipants gets a reference to the given NullableInt32 and assigns it to the MinParticipants field.
func (o *PlannedCoursePayload) SetMinParticipants(v int32) {
	o.MinParticipants.Set(&v)
}
// SetMinParticipantsNil sets the value for MinParticipants to be an explicit nil
func (o *PlannedCoursePayload) SetMinParticipantsNil() {
	o.MinParticipants.Set(nil)
}

// UnsetMinParticipants ensures that no value is present for MinParticipants, not even an explicit nil
func (o *PlannedCoursePayload) UnsetMinParticipants() {
	o.MinParticipants.Unset()
}

// GetMaxParticipants returns the MaxParticipants field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PlannedCoursePayload) GetMaxParticipants() int32 {
	if o == nil || IsNil(o.MaxParticipants.Get()) {
		var ret int32
		return ret
	}
	return *o.MaxParticipants.Get()
}

// GetMaxParticipantsOk returns a tuple with the MaxParticipants field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PlannedCoursePayload) GetMaxParticipantsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.MaxParticipants.Get(), o.MaxParticipants.IsSet()
}

// HasMaxParticipants returns a boolean if a field has been set.
func (o *PlannedCoursePayload) HasMaxParticipants() bool {
	if o != nil && o.MaxParticipants.IsSet() {
		return true
	}

	return false
}

// SetMaxParticipants gets a reference to the given NullableInt32 and assigns it to the MaxParticipants field.
func (o *PlannedCoursePayload) SetMaxParticipants(v int32) {
	o.MaxParticipants.Set(&v)
}
// SetMaxParticipantsNil sets the value for MaxParticipants to be an explicit nil
func (o *PlannedCoursePayload) SetMaxParticipantsNil() {
	o.MaxParticipants.Set(nil)
}

// UnsetMaxParticipants ensures that no value is present for MaxParticipants, not even an explicit nil
func (o *PlannedCoursePayload) UnsetMaxParticipants() {
	o.MaxParticipants.Unset()
}

// GetCostScheme returns the CostScheme field value if set, zero value otherwise.
func (o *PlannedCoursePayload) GetCostScheme() string {
	if o == nil || IsNil(o.CostScheme) {
		var ret string
		return ret
	}
	return *o.CostScheme
}

// GetCostSchemeOk returns a tuple with the CostScheme field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlannedCoursePayload) GetCostSchemeOk() (*string, bool) {
	if o == nil || IsNil(o.CostScheme) {
		return nil, false
	}
	return o.CostScheme, true
}

// HasCostScheme returns a boolean if a field has been set.
func (o *PlannedCoursePayload) HasCostScheme() bool {
	if o != nil && !IsNil(o.CostScheme) {
		return true
	}

	return false
}

// SetCostScheme gets a reference to the given string and assigns it to the CostScheme field.
func (o *PlannedCoursePayload) SetCostScheme(v string) {
	o.CostScheme = &v
}

// GetCost returns the Cost field value
// If the value is explicit nil, the zero value for float32 will be returned
func (o *PlannedCoursePayload) GetCost() float32 {
	if o == nil || o.Cost.Get() == nil {
		var ret float32
		return ret
	}

	return *o.Cost.Get()
}

// GetCostOk returns a tuple with the Cost field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PlannedCoursePayload) GetCostOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Cost.Get(), o.Cost.IsSet()
}

// SetCost sets field value
func (o *PlannedCoursePayload) SetCost(v float32) {
	o.Cost.Set(&v)
}

// GetCourseVariantId returns the CourseVariantId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PlannedCoursePayload) GetCourseVariantId() int32 {
	if o == nil || IsNil(o.CourseVariantId.Get()) {
		var ret int32
		return ret
	}
	return *o.CourseVariantId.Get()
}

// GetCourseVariantIdOk returns a tuple with the CourseVariantId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PlannedCoursePayload) GetCourseVariantIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.CourseVariantId.Get(), o.CourseVariantId.IsSet()
}

// HasCourseVariantId returns a boolean if a field has been set.
func (o *PlannedCoursePayload) HasCourseVariantId() bool {
	if o != nil && o.CourseVariantId.IsSet() {
		return true
	}

	return false
}

// SetCourseVariantId gets a reference to the given NullableInt32 and assigns it to the CourseVariantId field.
func (o *PlannedCoursePayload) SetCourseVariantId(v int32) {
	o.CourseVariantId.Set(&v)
}
// SetCourseVariantIdNil sets the value for CourseVariantId to be an explicit nil
func (o *PlannedCoursePayload) SetCourseVariantIdNil() {
	o.CourseVariantId.Set(nil)
}

// UnsetCourseVariantId ensures that no value is present for CourseVariantId, not even an explicit nil
func (o *PlannedCoursePayload) UnsetCourseVariantId() {
	o.CourseVariantId.Unset()
}

// GetCourseLocationId returns the CourseLocationId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PlannedCoursePayload) GetCourseLocationId() int32 {
	if o == nil || IsNil(o.CourseLocationId.Get()) {
		var ret int32
		return ret
	}
	return *o.CourseLocationId.Get()
}

// GetCourseLocationIdOk returns a tuple with the CourseLocationId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PlannedCoursePayload) GetCourseLocationIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.CourseLocationId.Get(), o.CourseLocationId.IsSet()
}

// HasCourseLocationId returns a boolean if a field has been set.
func (o *PlannedCoursePayload) HasCourseLocationId() bool {
	if o != nil && o.CourseLocationId.IsSet() {
		return true
	}

	return false
}

// SetCourseLocationId gets a reference to the given NullableInt32 and assigns it to the CourseLocationId field.
func (o *PlannedCoursePayload) SetCourseLocationId(v int32) {
	o.CourseLocationId.Set(&v)
}
// SetCourseLocationIdNil sets the value for CourseLocationId to be an explicit nil
func (o *PlannedCoursePayload) SetCourseLocationIdNil() {
	o.CourseLocationId.Set(nil)
}

// UnsetCourseLocationId ensures that no value is present for CourseLocationId, not even an explicit nil
func (o *PlannedCoursePayload) UnsetCourseLocationId() {
	o.CourseLocationId.Unset()
}

// GetDuration returns the Duration field value if set, zero value otherwise.
func (o *PlannedCoursePayload) GetDuration() float32 {
	if o == nil || IsNil(o.Duration) {
		var ret float32
		return ret
	}
	return *o.Duration
}

// GetDurationOk returns a tuple with the Duration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlannedCoursePayload) GetDurationOk() (*float32, bool) {
	if o == nil || IsNil(o.Duration) {
		return nil, false
	}
	return o.Duration, true
}

// HasDuration returns a boolean if a field has been set.
func (o *PlannedCoursePayload) HasDuration() bool {
	if o != nil && !IsNil(o.Duration) {
		return true
	}

	return false
}

// SetDuration gets a reference to the given float32 and assigns it to the Duration field.
func (o *PlannedCoursePayload) SetDuration(v float32) {
	o.Duration = &v
}

// GetTeacherIds returns the TeacherIds field value if set, zero value otherwise.
func (o *PlannedCoursePayload) GetTeacherIds() []int32 {
	if o == nil || IsNil(o.TeacherIds) {
		var ret []int32
		return ret
	}
	return o.TeacherIds
}

// GetTeacherIdsOk returns a tuple with the TeacherIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlannedCoursePayload) GetTeacherIdsOk() ([]int32, bool) {
	if o == nil || IsNil(o.TeacherIds) {
		return nil, false
	}
	return o.TeacherIds, true
}

// HasTeacherIds returns a boolean if a field has been set.
func (o *PlannedCoursePayload) HasTeacherIds() bool {
	if o != nil && !IsNil(o.TeacherIds) {
		return true
	}

	return false
}

// SetTeacherIds gets a reference to the given []int32 and assigns it to the TeacherIds field.
func (o *PlannedCoursePayload) SetTeacherIds(v []int32) {
	o.TeacherIds = v
}

// GetCustom returns the Custom field value if set, zero value otherwise.
func (o *PlannedCoursePayload) GetCustom() map[string]interface{} {
	if o == nil || IsNil(o.Custom) {
		var ret map[string]interface{}
		return ret
	}
	return o.Custom
}

// GetCustomOk returns a tuple with the Custom field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlannedCoursePayload) GetCustomOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Custom) {
		return map[string]interface{}{}, false
	}
	return o.Custom, true
}

// HasCustom returns a boolean if a field has been set.
func (o *PlannedCoursePayload) HasCustom() bool {
	if o != nil && !IsNil(o.Custom) {
		return true
	}

	return false
}

// SetCustom gets a reference to the given map[string]interface{} and assigns it to the Custom field.
func (o *PlannedCoursePayload) SetCustom(v map[string]interface{}) {
	o.Custom = v
}

// GetCustomAssociations returns the CustomAssociations field value if set, zero value otherwise.
func (o *PlannedCoursePayload) GetCustomAssociations() []CustomAssociationsRecordsPayload {
	if o == nil || IsNil(o.CustomAssociations) {
		var ret []CustomAssociationsRecordsPayload
		return ret
	}
	return o.CustomAssociations
}

// GetCustomAssociationsOk returns a tuple with the CustomAssociations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlannedCoursePayload) GetCustomAssociationsOk() ([]CustomAssociationsRecordsPayload, bool) {
	if o == nil || IsNil(o.CustomAssociations) {
		return nil, false
	}
	return o.CustomAssociations, true
}

// HasCustomAssociations returns a boolean if a field has been set.
func (o *PlannedCoursePayload) HasCustomAssociations() bool {
	if o != nil && !IsNil(o.CustomAssociations) {
		return true
	}

	return false
}

// SetCustomAssociations gets a reference to the given []CustomAssociationsRecordsPayload and assigns it to the CustomAssociations field.
func (o *PlannedCoursePayload) SetCustomAssociations(v []CustomAssociationsRecordsPayload) {
	o.CustomAssociations = v
}

func (o PlannedCoursePayload) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PlannedCoursePayload) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.IsPublished) {
		toSerialize["is_published"] = o.IsPublished
	}
	toSerialize["course_id"] = o.CourseId
	toSerialize["type"] = o.Type
	if !IsNil(o.StartDate) {
		toSerialize["start_date"] = o.StartDate
	}
	if o.EndDate.IsSet() {
		toSerialize["end_date"] = o.EndDate.Get()
	}
	if o.MinParticipants.IsSet() {
		toSerialize["min_participants"] = o.MinParticipants.Get()
	}
	if o.MaxParticipants.IsSet() {
		toSerialize["max_participants"] = o.MaxParticipants.Get()
	}
	if !IsNil(o.CostScheme) {
		toSerialize["cost_scheme"] = o.CostScheme
	}
	toSerialize["cost"] = o.Cost.Get()
	if o.CourseVariantId.IsSet() {
		toSerialize["course_variant_id"] = o.CourseVariantId.Get()
	}
	if o.CourseLocationId.IsSet() {
		toSerialize["course_location_id"] = o.CourseLocationId.Get()
	}
	if !IsNil(o.Duration) {
		toSerialize["duration"] = o.Duration
	}
	if !IsNil(o.TeacherIds) {
		toSerialize["teacher_ids"] = o.TeacherIds
	}
	if !IsNil(o.Custom) {
		toSerialize["custom"] = o.Custom
	}
	if !IsNil(o.CustomAssociations) {
		toSerialize["custom_associations"] = o.CustomAssociations
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PlannedCoursePayload) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"course_id",
		"type",
		"cost",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPlannedCoursePayload := _PlannedCoursePayload{}

	err = json.Unmarshal(data, &varPlannedCoursePayload)

	if err != nil {
		return err
	}

	*o = PlannedCoursePayload(varPlannedCoursePayload)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "is_published")
		delete(additionalProperties, "course_id")
		delete(additionalProperties, "type")
		delete(additionalProperties, "start_date")
		delete(additionalProperties, "end_date")
		delete(additionalProperties, "min_participants")
		delete(additionalProperties, "max_participants")
		delete(additionalProperties, "cost_scheme")
		delete(additionalProperties, "cost")
		delete(additionalProperties, "course_variant_id")
		delete(additionalProperties, "course_location_id")
		delete(additionalProperties, "duration")
		delete(additionalProperties, "teacher_ids")
		delete(additionalProperties, "custom")
		delete(additionalProperties, "custom_associations")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePlannedCoursePayload struct {
	value *PlannedCoursePayload
	isSet bool
}

func (v NullablePlannedCoursePayload) Get() *PlannedCoursePayload {
	return v.value
}

func (v *NullablePlannedCoursePayload) Set(val *PlannedCoursePayload) {
	v.value = val
	v.isSet = true
}

func (v NullablePlannedCoursePayload) IsSet() bool {
	return v.isSet
}

func (v *NullablePlannedCoursePayload) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePlannedCoursePayload(val *PlannedCoursePayload) *NullablePlannedCoursePayload {
	return &NullablePlannedCoursePayload{value: val, isSet: true}
}

func (v NullablePlannedCoursePayload) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePlannedCoursePayload) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


