/*
Eduframe - API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package eduframe

import (
	"encoding/json"
	"fmt"
)

// checks if the ProgramEditionBlockElement type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProgramEditionBlockElement{}

// ProgramEditionBlockElement struct for ProgramEditionBlockElement
type ProgramEditionBlockElement struct {
	// The name of the element.
	Name string `json:"name"`
	// The credits of the element.
	Credits NullableFloat64 `json:"credits"`
	// The type of the element.
	ElementType string `json:"element_type"`
	// The elements of the block element.
	Elements []ProgramEditionBlockElementItem `json:"elements"`
	AdditionalProperties map[string]interface{}
}

type _ProgramEditionBlockElement ProgramEditionBlockElement

// NewProgramEditionBlockElement instantiates a new ProgramEditionBlockElement object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProgramEditionBlockElement(name string, credits NullableFloat64, elementType string, elements []ProgramEditionBlockElementItem) *ProgramEditionBlockElement {
	this := ProgramEditionBlockElement{}
	this.Name = name
	this.Credits = credits
	this.ElementType = elementType
	this.Elements = elements
	return &this
}

// NewProgramEditionBlockElementWithDefaults instantiates a new ProgramEditionBlockElement object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProgramEditionBlockElementWithDefaults() *ProgramEditionBlockElement {
	this := ProgramEditionBlockElement{}
	return &this
}

// GetName returns the Name field value
func (o *ProgramEditionBlockElement) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ProgramEditionBlockElement) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ProgramEditionBlockElement) SetName(v string) {
	o.Name = v
}

// GetCredits returns the Credits field value
// If the value is explicit nil, the zero value for float64 will be returned
func (o *ProgramEditionBlockElement) GetCredits() float64 {
	if o == nil || o.Credits.Get() == nil {
		var ret float64
		return ret
	}

	return *o.Credits.Get()
}

// GetCreditsOk returns a tuple with the Credits field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ProgramEditionBlockElement) GetCreditsOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return o.Credits.Get(), o.Credits.IsSet()
}

// SetCredits sets field value
func (o *ProgramEditionBlockElement) SetCredits(v float64) {
	o.Credits.Set(&v)
}

// GetElementType returns the ElementType field value
func (o *ProgramEditionBlockElement) GetElementType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ElementType
}

// GetElementTypeOk returns a tuple with the ElementType field value
// and a boolean to check if the value has been set.
func (o *ProgramEditionBlockElement) GetElementTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ElementType, true
}

// SetElementType sets field value
func (o *ProgramEditionBlockElement) SetElementType(v string) {
	o.ElementType = v
}

// GetElements returns the Elements field value
func (o *ProgramEditionBlockElement) GetElements() []ProgramEditionBlockElementItem {
	if o == nil {
		var ret []ProgramEditionBlockElementItem
		return ret
	}

	return o.Elements
}

// GetElementsOk returns a tuple with the Elements field value
// and a boolean to check if the value has been set.
func (o *ProgramEditionBlockElement) GetElementsOk() ([]ProgramEditionBlockElementItem, bool) {
	if o == nil {
		return nil, false
	}
	return o.Elements, true
}

// SetElements sets field value
func (o *ProgramEditionBlockElement) SetElements(v []ProgramEditionBlockElementItem) {
	o.Elements = v
}

func (o ProgramEditionBlockElement) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProgramEditionBlockElement) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["credits"] = o.Credits.Get()
	toSerialize["element_type"] = o.ElementType
	toSerialize["elements"] = o.Elements

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ProgramEditionBlockElement) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"credits",
		"element_type",
		"elements",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varProgramEditionBlockElement := _ProgramEditionBlockElement{}

	err = json.Unmarshal(data, &varProgramEditionBlockElement)

	if err != nil {
		return err
	}

	*o = ProgramEditionBlockElement(varProgramEditionBlockElement)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "credits")
		delete(additionalProperties, "element_type")
		delete(additionalProperties, "elements")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableProgramEditionBlockElement struct {
	value *ProgramEditionBlockElement
	isSet bool
}

func (v NullableProgramEditionBlockElement) Get() *ProgramEditionBlockElement {
	return v.value
}

func (v *NullableProgramEditionBlockElement) Set(val *ProgramEditionBlockElement) {
	v.value = val
	v.isSet = true
}

func (v NullableProgramEditionBlockElement) IsSet() bool {
	return v.isSet
}

func (v *NullableProgramEditionBlockElement) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProgramEditionBlockElement(val *ProgramEditionBlockElement) *NullableProgramEditionBlockElement {
	return &NullableProgramEditionBlockElement{value: val, isSet: true}
}

func (v NullableProgramEditionBlockElement) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProgramEditionBlockElement) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


