/*
Eduframe - API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package eduframe

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ProgramProgramPayload type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProgramProgramPayload{}

// ProgramProgramPayload struct for ProgramProgramPayload
type ProgramProgramPayload struct {
	// Name of the program.
	Name string `json:"name"`
	// Identifier of the category of the program.
	CategoryId int32 `json:"category_id"`
	// How should the program be paid by default.
	CostScheme string `json:"cost_scheme"`
	// The price to be paid for this program. Required if cost_scheme is student (default value) or order.
	Cost NullableInt32 `json:"cost,omitempty"`
	// Boolean representing the publishable status of the program.
	IsPublished *bool `json:"is_published,omitempty"`
	// IDs of the labels
	LabelIds []int32 `json:"label_ids,omitempty"`
	// The custom properties of the program.
	Custom map[string]interface{} `json:"custom,omitempty"`
	// Custom associations are a way to link custom records to a program.  ![Custom Objects](https://img.shields.io/badge/Feature-Custom_objects-1d8127) 
	CustomAssociations []CustomAssociationsRecordsPayload `json:"custom_associations,omitempty"`
	CourseTabContentsAttributes []CoursePayloadCourseTabContentsAttributesInner `json:"course_tab_contents_attributes,omitempty"`
}

type _ProgramProgramPayload ProgramProgramPayload

// NewProgramProgramPayload instantiates a new ProgramProgramPayload object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProgramProgramPayload(name string, categoryId int32, costScheme string) *ProgramProgramPayload {
	this := ProgramProgramPayload{}
	this.Name = name
	this.CategoryId = categoryId
	this.CostScheme = costScheme
	return &this
}

// NewProgramProgramPayloadWithDefaults instantiates a new ProgramProgramPayload object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProgramProgramPayloadWithDefaults() *ProgramProgramPayload {
	this := ProgramProgramPayload{}
	return &this
}

// GetName returns the Name field value
func (o *ProgramProgramPayload) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ProgramProgramPayload) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ProgramProgramPayload) SetName(v string) {
	o.Name = v
}

// GetCategoryId returns the CategoryId field value
func (o *ProgramProgramPayload) GetCategoryId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.CategoryId
}

// GetCategoryIdOk returns a tuple with the CategoryId field value
// and a boolean to check if the value has been set.
func (o *ProgramProgramPayload) GetCategoryIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CategoryId, true
}

// SetCategoryId sets field value
func (o *ProgramProgramPayload) SetCategoryId(v int32) {
	o.CategoryId = v
}

// GetCostScheme returns the CostScheme field value
func (o *ProgramProgramPayload) GetCostScheme() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CostScheme
}

// GetCostSchemeOk returns a tuple with the CostScheme field value
// and a boolean to check if the value has been set.
func (o *ProgramProgramPayload) GetCostSchemeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CostScheme, true
}

// SetCostScheme sets field value
func (o *ProgramProgramPayload) SetCostScheme(v string) {
	o.CostScheme = v
}

// GetCost returns the Cost field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ProgramProgramPayload) GetCost() int32 {
	if o == nil || IsNil(o.Cost.Get()) {
		var ret int32
		return ret
	}
	return *o.Cost.Get()
}

// GetCostOk returns a tuple with the Cost field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ProgramProgramPayload) GetCostOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Cost.Get(), o.Cost.IsSet()
}

// HasCost returns a boolean if a field has been set.
func (o *ProgramProgramPayload) HasCost() bool {
	if o != nil && o.Cost.IsSet() {
		return true
	}

	return false
}

// SetCost gets a reference to the given NullableInt32 and assigns it to the Cost field.
func (o *ProgramProgramPayload) SetCost(v int32) {
	o.Cost.Set(&v)
}
// SetCostNil sets the value for Cost to be an explicit nil
func (o *ProgramProgramPayload) SetCostNil() {
	o.Cost.Set(nil)
}

// UnsetCost ensures that no value is present for Cost, not even an explicit nil
func (o *ProgramProgramPayload) UnsetCost() {
	o.Cost.Unset()
}

// GetIsPublished returns the IsPublished field value if set, zero value otherwise.
func (o *ProgramProgramPayload) GetIsPublished() bool {
	if o == nil || IsNil(o.IsPublished) {
		var ret bool
		return ret
	}
	return *o.IsPublished
}

// GetIsPublishedOk returns a tuple with the IsPublished field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProgramProgramPayload) GetIsPublishedOk() (*bool, bool) {
	if o == nil || IsNil(o.IsPublished) {
		return nil, false
	}
	return o.IsPublished, true
}

// HasIsPublished returns a boolean if a field has been set.
func (o *ProgramProgramPayload) HasIsPublished() bool {
	if o != nil && !IsNil(o.IsPublished) {
		return true
	}

	return false
}

// SetIsPublished gets a reference to the given bool and assigns it to the IsPublished field.
func (o *ProgramProgramPayload) SetIsPublished(v bool) {
	o.IsPublished = &v
}

// GetLabelIds returns the LabelIds field value if set, zero value otherwise.
func (o *ProgramProgramPayload) GetLabelIds() []int32 {
	if o == nil || IsNil(o.LabelIds) {
		var ret []int32
		return ret
	}
	return o.LabelIds
}

// GetLabelIdsOk returns a tuple with the LabelIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProgramProgramPayload) GetLabelIdsOk() ([]int32, bool) {
	if o == nil || IsNil(o.LabelIds) {
		return nil, false
	}
	return o.LabelIds, true
}

// HasLabelIds returns a boolean if a field has been set.
func (o *ProgramProgramPayload) HasLabelIds() bool {
	if o != nil && !IsNil(o.LabelIds) {
		return true
	}

	return false
}

// SetLabelIds gets a reference to the given []int32 and assigns it to the LabelIds field.
func (o *ProgramProgramPayload) SetLabelIds(v []int32) {
	o.LabelIds = v
}

// GetCustom returns the Custom field value if set, zero value otherwise.
func (o *ProgramProgramPayload) GetCustom() map[string]interface{} {
	if o == nil || IsNil(o.Custom) {
		var ret map[string]interface{}
		return ret
	}
	return o.Custom
}

// GetCustomOk returns a tuple with the Custom field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProgramProgramPayload) GetCustomOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Custom) {
		return map[string]interface{}{}, false
	}
	return o.Custom, true
}

// HasCustom returns a boolean if a field has been set.
func (o *ProgramProgramPayload) HasCustom() bool {
	if o != nil && !IsNil(o.Custom) {
		return true
	}

	return false
}

// SetCustom gets a reference to the given map[string]interface{} and assigns it to the Custom field.
func (o *ProgramProgramPayload) SetCustom(v map[string]interface{}) {
	o.Custom = v
}

// GetCustomAssociations returns the CustomAssociations field value if set, zero value otherwise.
func (o *ProgramProgramPayload) GetCustomAssociations() []CustomAssociationsRecordsPayload {
	if o == nil || IsNil(o.CustomAssociations) {
		var ret []CustomAssociationsRecordsPayload
		return ret
	}
	return o.CustomAssociations
}

// GetCustomAssociationsOk returns a tuple with the CustomAssociations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProgramProgramPayload) GetCustomAssociationsOk() ([]CustomAssociationsRecordsPayload, bool) {
	if o == nil || IsNil(o.CustomAssociations) {
		return nil, false
	}
	return o.CustomAssociations, true
}

// HasCustomAssociations returns a boolean if a field has been set.
func (o *ProgramProgramPayload) HasCustomAssociations() bool {
	if o != nil && !IsNil(o.CustomAssociations) {
		return true
	}

	return false
}

// SetCustomAssociations gets a reference to the given []CustomAssociationsRecordsPayload and assigns it to the CustomAssociations field.
func (o *ProgramProgramPayload) SetCustomAssociations(v []CustomAssociationsRecordsPayload) {
	o.CustomAssociations = v
}

// GetCourseTabContentsAttributes returns the CourseTabContentsAttributes field value if set, zero value otherwise.
func (o *ProgramProgramPayload) GetCourseTabContentsAttributes() []CoursePayloadCourseTabContentsAttributesInner {
	if o == nil || IsNil(o.CourseTabContentsAttributes) {
		var ret []CoursePayloadCourseTabContentsAttributesInner
		return ret
	}
	return o.CourseTabContentsAttributes
}

// GetCourseTabContentsAttributesOk returns a tuple with the CourseTabContentsAttributes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProgramProgramPayload) GetCourseTabContentsAttributesOk() ([]CoursePayloadCourseTabContentsAttributesInner, bool) {
	if o == nil || IsNil(o.CourseTabContentsAttributes) {
		return nil, false
	}
	return o.CourseTabContentsAttributes, true
}

// HasCourseTabContentsAttributes returns a boolean if a field has been set.
func (o *ProgramProgramPayload) HasCourseTabContentsAttributes() bool {
	if o != nil && !IsNil(o.CourseTabContentsAttributes) {
		return true
	}

	return false
}

// SetCourseTabContentsAttributes gets a reference to the given []CoursePayloadCourseTabContentsAttributesInner and assigns it to the CourseTabContentsAttributes field.
func (o *ProgramProgramPayload) SetCourseTabContentsAttributes(v []CoursePayloadCourseTabContentsAttributesInner) {
	o.CourseTabContentsAttributes = v
}

func (o ProgramProgramPayload) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProgramProgramPayload) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["category_id"] = o.CategoryId
	toSerialize["cost_scheme"] = o.CostScheme
	if o.Cost.IsSet() {
		toSerialize["cost"] = o.Cost.Get()
	}
	if !IsNil(o.IsPublished) {
		toSerialize["is_published"] = o.IsPublished
	}
	if !IsNil(o.LabelIds) {
		toSerialize["label_ids"] = o.LabelIds
	}
	if !IsNil(o.Custom) {
		toSerialize["custom"] = o.Custom
	}
	if !IsNil(o.CustomAssociations) {
		toSerialize["custom_associations"] = o.CustomAssociations
	}
	if !IsNil(o.CourseTabContentsAttributes) {
		toSerialize["course_tab_contents_attributes"] = o.CourseTabContentsAttributes
	}
	return toSerialize, nil
}

func (o *ProgramProgramPayload) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"category_id",
		"cost_scheme",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varProgramProgramPayload := _ProgramProgramPayload{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varProgramProgramPayload)

	if err != nil {
		return err
	}

	*o = ProgramProgramPayload(varProgramProgramPayload)

	return err
}

type NullableProgramProgramPayload struct {
	value *ProgramProgramPayload
	isSet bool
}

func (v NullableProgramProgramPayload) Get() *ProgramProgramPayload {
	return v.value
}

func (v *NullableProgramProgramPayload) Set(val *ProgramProgramPayload) {
	v.value = val
	v.isSet = true
}

func (v NullableProgramProgramPayload) IsSet() bool {
	return v.isSet
}

func (v *NullableProgramProgramPayload) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProgramProgramPayload(val *ProgramProgramPayload) *NullableProgramProgramPayload {
	return &NullableProgramProgramPayload{value: val, isSet: true}
}

func (v NullableProgramProgramPayload) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProgramProgramPayload) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


