/*
Eduframe - API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package eduframe

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreditCategory type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreditCategory{}

// CreditCategory struct for CreditCategory
type CreditCategory struct {
	// Unique identifier of the credit category.
	Id int32 `json:"id"`
	// Name of the credit category.
	Name string `json:"name"`
}

type _CreditCategory CreditCategory

// NewCreditCategory instantiates a new CreditCategory object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreditCategory(id int32, name string) *CreditCategory {
	this := CreditCategory{}
	this.Id = id
	this.Name = name
	return &this
}

// NewCreditCategoryWithDefaults instantiates a new CreditCategory object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreditCategoryWithDefaults() *CreditCategory {
	this := CreditCategory{}
	return &this
}

// GetId returns the Id field value
func (o *CreditCategory) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *CreditCategory) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *CreditCategory) SetId(v int32) {
	o.Id = v
}

// GetName returns the Name field value
func (o *CreditCategory) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreditCategory) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreditCategory) SetName(v string) {
	o.Name = v
}

func (o CreditCategory) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreditCategory) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	return toSerialize, nil
}

func (o *CreditCategory) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreditCategory := _CreditCategory{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreditCategory)

	if err != nil {
		return err
	}

	*o = CreditCategory(varCreditCategory)

	return err
}

type NullableCreditCategory struct {
	value *CreditCategory
	isSet bool
}

func (v NullableCreditCategory) Get() *CreditCategory {
	return v.value
}

func (v *NullableCreditCategory) Set(val *CreditCategory) {
	v.value = val
	v.isSet = true
}

func (v NullableCreditCategory) IsSet() bool {
	return v.isSet
}

func (v *NullableCreditCategory) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreditCategory(val *CreditCategory) *NullableCreditCategory {
	return &NullableCreditCategory{value: val, isSet: true}
}

func (v NullableCreditCategory) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreditCategory) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


