/*
Eduframe - API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package eduframe

import (
	"encoding/json"
	"fmt"
)

// checks if the CoursePayloadCourseTabContentsAttributesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CoursePayloadCourseTabContentsAttributesInner{}

// CoursePayloadCourseTabContentsAttributesInner struct for CoursePayloadCourseTabContentsAttributesInner
type CoursePayloadCourseTabContentsAttributesInner struct {
	// The HTML content of the course tab.
	Content NullableString `json:"content"`
	// Unique identifier of the course tab.
	CourseTabId int32 `json:"course_tab_id"`
	AdditionalProperties map[string]interface{}
}

type _CoursePayloadCourseTabContentsAttributesInner CoursePayloadCourseTabContentsAttributesInner

// NewCoursePayloadCourseTabContentsAttributesInner instantiates a new CoursePayloadCourseTabContentsAttributesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCoursePayloadCourseTabContentsAttributesInner(content NullableString, courseTabId int32) *CoursePayloadCourseTabContentsAttributesInner {
	this := CoursePayloadCourseTabContentsAttributesInner{}
	this.Content = content
	this.CourseTabId = courseTabId
	return &this
}

// NewCoursePayloadCourseTabContentsAttributesInnerWithDefaults instantiates a new CoursePayloadCourseTabContentsAttributesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCoursePayloadCourseTabContentsAttributesInnerWithDefaults() *CoursePayloadCourseTabContentsAttributesInner {
	this := CoursePayloadCourseTabContentsAttributesInner{}
	return &this
}

// GetContent returns the Content field value
// If the value is explicit nil, the zero value for string will be returned
func (o *CoursePayloadCourseTabContentsAttributesInner) GetContent() string {
	if o == nil || o.Content.Get() == nil {
		var ret string
		return ret
	}

	return *o.Content.Get()
}

// GetContentOk returns a tuple with the Content field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CoursePayloadCourseTabContentsAttributesInner) GetContentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Content.Get(), o.Content.IsSet()
}

// SetContent sets field value
func (o *CoursePayloadCourseTabContentsAttributesInner) SetContent(v string) {
	o.Content.Set(&v)
}

// GetCourseTabId returns the CourseTabId field value
func (o *CoursePayloadCourseTabContentsAttributesInner) GetCourseTabId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.CourseTabId
}

// GetCourseTabIdOk returns a tuple with the CourseTabId field value
// and a boolean to check if the value has been set.
func (o *CoursePayloadCourseTabContentsAttributesInner) GetCourseTabIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CourseTabId, true
}

// SetCourseTabId sets field value
func (o *CoursePayloadCourseTabContentsAttributesInner) SetCourseTabId(v int32) {
	o.CourseTabId = v
}

func (o CoursePayloadCourseTabContentsAttributesInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CoursePayloadCourseTabContentsAttributesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["content"] = o.Content.Get()
	toSerialize["course_tab_id"] = o.CourseTabId

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CoursePayloadCourseTabContentsAttributesInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"content",
		"course_tab_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCoursePayloadCourseTabContentsAttributesInner := _CoursePayloadCourseTabContentsAttributesInner{}

	err = json.Unmarshal(data, &varCoursePayloadCourseTabContentsAttributesInner)

	if err != nil {
		return err
	}

	*o = CoursePayloadCourseTabContentsAttributesInner(varCoursePayloadCourseTabContentsAttributesInner)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "content")
		delete(additionalProperties, "course_tab_id")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCoursePayloadCourseTabContentsAttributesInner struct {
	value *CoursePayloadCourseTabContentsAttributesInner
	isSet bool
}

func (v NullableCoursePayloadCourseTabContentsAttributesInner) Get() *CoursePayloadCourseTabContentsAttributesInner {
	return v.value
}

func (v *NullableCoursePayloadCourseTabContentsAttributesInner) Set(val *CoursePayloadCourseTabContentsAttributesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableCoursePayloadCourseTabContentsAttributesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableCoursePayloadCourseTabContentsAttributesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCoursePayloadCourseTabContentsAttributesInner(val *CoursePayloadCourseTabContentsAttributesInner) *NullableCoursePayloadCourseTabContentsAttributesInner {
	return &NullableCoursePayloadCourseTabContentsAttributesInner{value: val, isSet: true}
}

func (v NullableCoursePayloadCourseTabContentsAttributesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCoursePayloadCourseTabContentsAttributesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


