/*
Eduframe - API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package eduframe

import (
	"encoding/json"
	"fmt"
)

// checks if the AddressPayload type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AddressPayload{}

// AddressPayload struct for AddressPayload
type AddressPayload struct {
	// The addressee of the address.
	Addressee NullableString `json:"addressee,omitempty"`
	// Concatenation of the street and house number.
	Address string `json:"address"`
	// A string representing the second line of the address.
	AddressLine2 NullableString `json:"address_line2,omitempty"`
	// A string representing the postal code.
	PostalCode string `json:"postal_code"`
	// A string representing the city.
	City string `json:"city"`
	StateProvince NullableUsaState `json:"state_province,omitempty"`
	Country Country `json:"country"`
	AdditionalProperties map[string]interface{}
}

type _AddressPayload AddressPayload

// NewAddressPayload instantiates a new AddressPayload object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAddressPayload(address string, postalCode string, city string, country Country) *AddressPayload {
	this := AddressPayload{}
	this.Address = address
	this.PostalCode = postalCode
	this.City = city
	this.Country = country
	return &this
}

// NewAddressPayloadWithDefaults instantiates a new AddressPayload object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddressPayloadWithDefaults() *AddressPayload {
	this := AddressPayload{}
	return &this
}

// GetAddressee returns the Addressee field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AddressPayload) GetAddressee() string {
	if o == nil || IsNil(o.Addressee.Get()) {
		var ret string
		return ret
	}
	return *o.Addressee.Get()
}

// GetAddresseeOk returns a tuple with the Addressee field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AddressPayload) GetAddresseeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Addressee.Get(), o.Addressee.IsSet()
}

// HasAddressee returns a boolean if a field has been set.
func (o *AddressPayload) HasAddressee() bool {
	if o != nil && o.Addressee.IsSet() {
		return true
	}

	return false
}

// SetAddressee gets a reference to the given NullableString and assigns it to the Addressee field.
func (o *AddressPayload) SetAddressee(v string) {
	o.Addressee.Set(&v)
}
// SetAddresseeNil sets the value for Addressee to be an explicit nil
func (o *AddressPayload) SetAddresseeNil() {
	o.Addressee.Set(nil)
}

// UnsetAddressee ensures that no value is present for Addressee, not even an explicit nil
func (o *AddressPayload) UnsetAddressee() {
	o.Addressee.Unset()
}

// GetAddress returns the Address field value
func (o *AddressPayload) GetAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Address
}

// GetAddressOk returns a tuple with the Address field value
// and a boolean to check if the value has been set.
func (o *AddressPayload) GetAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Address, true
}

// SetAddress sets field value
func (o *AddressPayload) SetAddress(v string) {
	o.Address = v
}

// GetAddressLine2 returns the AddressLine2 field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AddressPayload) GetAddressLine2() string {
	if o == nil || IsNil(o.AddressLine2.Get()) {
		var ret string
		return ret
	}
	return *o.AddressLine2.Get()
}

// GetAddressLine2Ok returns a tuple with the AddressLine2 field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AddressPayload) GetAddressLine2Ok() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AddressLine2.Get(), o.AddressLine2.IsSet()
}

// HasAddressLine2 returns a boolean if a field has been set.
func (o *AddressPayload) HasAddressLine2() bool {
	if o != nil && o.AddressLine2.IsSet() {
		return true
	}

	return false
}

// SetAddressLine2 gets a reference to the given NullableString and assigns it to the AddressLine2 field.
func (o *AddressPayload) SetAddressLine2(v string) {
	o.AddressLine2.Set(&v)
}
// SetAddressLine2Nil sets the value for AddressLine2 to be an explicit nil
func (o *AddressPayload) SetAddressLine2Nil() {
	o.AddressLine2.Set(nil)
}

// UnsetAddressLine2 ensures that no value is present for AddressLine2, not even an explicit nil
func (o *AddressPayload) UnsetAddressLine2() {
	o.AddressLine2.Unset()
}

// GetPostalCode returns the PostalCode field value
func (o *AddressPayload) GetPostalCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PostalCode
}

// GetPostalCodeOk returns a tuple with the PostalCode field value
// and a boolean to check if the value has been set.
func (o *AddressPayload) GetPostalCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PostalCode, true
}

// SetPostalCode sets field value
func (o *AddressPayload) SetPostalCode(v string) {
	o.PostalCode = v
}

// GetCity returns the City field value
func (o *AddressPayload) GetCity() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.City
}

// GetCityOk returns a tuple with the City field value
// and a boolean to check if the value has been set.
func (o *AddressPayload) GetCityOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.City, true
}

// SetCity sets field value
func (o *AddressPayload) SetCity(v string) {
	o.City = v
}

// GetStateProvince returns the StateProvince field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AddressPayload) GetStateProvince() UsaState {
	if o == nil || IsNil(o.StateProvince.Get()) {
		var ret UsaState
		return ret
	}
	return *o.StateProvince.Get()
}

// GetStateProvinceOk returns a tuple with the StateProvince field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AddressPayload) GetStateProvinceOk() (*UsaState, bool) {
	if o == nil {
		return nil, false
	}
	return o.StateProvince.Get(), o.StateProvince.IsSet()
}

// HasStateProvince returns a boolean if a field has been set.
func (o *AddressPayload) HasStateProvince() bool {
	if o != nil && o.StateProvince.IsSet() {
		return true
	}

	return false
}

// SetStateProvince gets a reference to the given NullableUsaState and assigns it to the StateProvince field.
func (o *AddressPayload) SetStateProvince(v UsaState) {
	o.StateProvince.Set(&v)
}
// SetStateProvinceNil sets the value for StateProvince to be an explicit nil
func (o *AddressPayload) SetStateProvinceNil() {
	o.StateProvince.Set(nil)
}

// UnsetStateProvince ensures that no value is present for StateProvince, not even an explicit nil
func (o *AddressPayload) UnsetStateProvince() {
	o.StateProvince.Unset()
}

// GetCountry returns the Country field value
func (o *AddressPayload) GetCountry() Country {
	if o == nil {
		var ret Country
		return ret
	}

	return o.Country
}

// GetCountryOk returns a tuple with the Country field value
// and a boolean to check if the value has been set.
func (o *AddressPayload) GetCountryOk() (*Country, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Country, true
}

// SetCountry sets field value
func (o *AddressPayload) SetCountry(v Country) {
	o.Country = v
}

func (o AddressPayload) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AddressPayload) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Addressee.IsSet() {
		toSerialize["addressee"] = o.Addressee.Get()
	}
	toSerialize["address"] = o.Address
	if o.AddressLine2.IsSet() {
		toSerialize["address_line2"] = o.AddressLine2.Get()
	}
	toSerialize["postal_code"] = o.PostalCode
	toSerialize["city"] = o.City
	if o.StateProvince.IsSet() {
		toSerialize["state_province"] = o.StateProvince.Get()
	}
	toSerialize["country"] = o.Country

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AddressPayload) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"address",
		"postal_code",
		"city",
		"country",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAddressPayload := _AddressPayload{}

	err = json.Unmarshal(data, &varAddressPayload)

	if err != nil {
		return err
	}

	*o = AddressPayload(varAddressPayload)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "addressee")
		delete(additionalProperties, "address")
		delete(additionalProperties, "address_line2")
		delete(additionalProperties, "postal_code")
		delete(additionalProperties, "city")
		delete(additionalProperties, "state_province")
		delete(additionalProperties, "country")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAddressPayload struct {
	value *AddressPayload
	isSet bool
}

func (v NullableAddressPayload) Get() *AddressPayload {
	return v.value
}

func (v *NullableAddressPayload) Set(val *AddressPayload) {
	v.value = val
	v.isSet = true
}

func (v NullableAddressPayload) IsSet() bool {
	return v.isSet
}

func (v *NullableAddressPayload) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddressPayload(val *AddressPayload) *NullableAddressPayload {
	return &NullableAddressPayload{value: val, isSet: true}
}

func (v NullableAddressPayload) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddressPayload) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


