/*
Eduframe - API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package eduframe

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the Affiliation type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Affiliation{}

// Affiliation struct for Affiliation
type Affiliation struct {
	// Unique identifier of the affiliation record.
	Id int32 `json:"id"`
	// Unique identifier of the associated account
	AccountId int32 `json:"account_id"`
	// Unique identifier of the associated user
	UserId int32 `json:"user_id"`
	// Boolean indicating if this user is a key contact of the account.
	KeyContact bool `json:"key_contact"`
	// Timestamp of last update.
	UpdatedAt time.Time `json:"updated_at"`
	// Timestamp of creation.
	CreatedAt time.Time `json:"created_at"`
}

type _Affiliation Affiliation

// NewAffiliation instantiates a new Affiliation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAffiliation(id int32, accountId int32, userId int32, keyContact bool, updatedAt time.Time, createdAt time.Time) *Affiliation {
	this := Affiliation{}
	this.Id = id
	this.AccountId = accountId
	this.UserId = userId
	this.KeyContact = keyContact
	this.UpdatedAt = updatedAt
	this.CreatedAt = createdAt
	return &this
}

// NewAffiliationWithDefaults instantiates a new Affiliation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAffiliationWithDefaults() *Affiliation {
	this := Affiliation{}
	var keyContact bool = false
	this.KeyContact = keyContact
	return &this
}

// GetId returns the Id field value
func (o *Affiliation) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *Affiliation) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *Affiliation) SetId(v int32) {
	o.Id = v
}

// GetAccountId returns the AccountId field value
func (o *Affiliation) GetAccountId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.AccountId
}

// GetAccountIdOk returns a tuple with the AccountId field value
// and a boolean to check if the value has been set.
func (o *Affiliation) GetAccountIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccountId, true
}

// SetAccountId sets field value
func (o *Affiliation) SetAccountId(v int32) {
	o.AccountId = v
}

// GetUserId returns the UserId field value
func (o *Affiliation) GetUserId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value
// and a boolean to check if the value has been set.
func (o *Affiliation) GetUserIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserId, true
}

// SetUserId sets field value
func (o *Affiliation) SetUserId(v int32) {
	o.UserId = v
}

// GetKeyContact returns the KeyContact field value
func (o *Affiliation) GetKeyContact() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.KeyContact
}

// GetKeyContactOk returns a tuple with the KeyContact field value
// and a boolean to check if the value has been set.
func (o *Affiliation) GetKeyContactOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.KeyContact, true
}

// SetKeyContact sets field value
func (o *Affiliation) SetKeyContact(v bool) {
	o.KeyContact = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *Affiliation) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *Affiliation) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *Affiliation) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *Affiliation) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *Affiliation) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *Affiliation) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

func (o Affiliation) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Affiliation) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["account_id"] = o.AccountId
	toSerialize["user_id"] = o.UserId
	toSerialize["key_contact"] = o.KeyContact
	toSerialize["updated_at"] = o.UpdatedAt
	toSerialize["created_at"] = o.CreatedAt
	return toSerialize, nil
}

func (o *Affiliation) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"account_id",
		"user_id",
		"key_contact",
		"updated_at",
		"created_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAffiliation := _Affiliation{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAffiliation)

	if err != nil {
		return err
	}

	*o = Affiliation(varAffiliation)

	return err
}

type NullableAffiliation struct {
	value *Affiliation
	isSet bool
}

func (v NullableAffiliation) Get() *Affiliation {
	return v.value
}

func (v *NullableAffiliation) Set(val *Affiliation) {
	v.value = val
	v.isSet = true
}

func (v NullableAffiliation) IsSet() bool {
	return v.isSet
}

func (v *NullableAffiliation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAffiliation(val *Affiliation) *NullableAffiliation {
	return &NullableAffiliation{value: val, isSet: true}
}

func (v NullableAffiliation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAffiliation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


