/*
Eduframe - API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package eduframe

import (
	"encoding/json"
	"fmt"
)

// checks if the CreateTeacherEnrollmentByPlannedCourseIdRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateTeacherEnrollmentByPlannedCourseIdRequest{}

// CreateTeacherEnrollmentByPlannedCourseIdRequest struct for CreateTeacherEnrollmentByPlannedCourseIdRequest
type CreateTeacherEnrollmentByPlannedCourseIdRequest struct {
	// Unique identifier of the teacher.
	TeacherId int32 `json:"teacher_id"`
	// Unique identifier of the teacher role.
	TeacherRoleId *int32 `json:"teacher_role_id,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CreateTeacherEnrollmentByPlannedCourseIdRequest CreateTeacherEnrollmentByPlannedCourseIdRequest

// NewCreateTeacherEnrollmentByPlannedCourseIdRequest instantiates a new CreateTeacherEnrollmentByPlannedCourseIdRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateTeacherEnrollmentByPlannedCourseIdRequest(teacherId int32) *CreateTeacherEnrollmentByPlannedCourseIdRequest {
	this := CreateTeacherEnrollmentByPlannedCourseIdRequest{}
	this.TeacherId = teacherId
	return &this
}

// NewCreateTeacherEnrollmentByPlannedCourseIdRequestWithDefaults instantiates a new CreateTeacherEnrollmentByPlannedCourseIdRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateTeacherEnrollmentByPlannedCourseIdRequestWithDefaults() *CreateTeacherEnrollmentByPlannedCourseIdRequest {
	this := CreateTeacherEnrollmentByPlannedCourseIdRequest{}
	return &this
}

// GetTeacherId returns the TeacherId field value
func (o *CreateTeacherEnrollmentByPlannedCourseIdRequest) GetTeacherId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TeacherId
}

// GetTeacherIdOk returns a tuple with the TeacherId field value
// and a boolean to check if the value has been set.
func (o *CreateTeacherEnrollmentByPlannedCourseIdRequest) GetTeacherIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TeacherId, true
}

// SetTeacherId sets field value
func (o *CreateTeacherEnrollmentByPlannedCourseIdRequest) SetTeacherId(v int32) {
	o.TeacherId = v
}

// GetTeacherRoleId returns the TeacherRoleId field value if set, zero value otherwise.
func (o *CreateTeacherEnrollmentByPlannedCourseIdRequest) GetTeacherRoleId() int32 {
	if o == nil || IsNil(o.TeacherRoleId) {
		var ret int32
		return ret
	}
	return *o.TeacherRoleId
}

// GetTeacherRoleIdOk returns a tuple with the TeacherRoleId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTeacherEnrollmentByPlannedCourseIdRequest) GetTeacherRoleIdOk() (*int32, bool) {
	if o == nil || IsNil(o.TeacherRoleId) {
		return nil, false
	}
	return o.TeacherRoleId, true
}

// HasTeacherRoleId returns a boolean if a field has been set.
func (o *CreateTeacherEnrollmentByPlannedCourseIdRequest) HasTeacherRoleId() bool {
	if o != nil && !IsNil(o.TeacherRoleId) {
		return true
	}

	return false
}

// SetTeacherRoleId gets a reference to the given int32 and assigns it to the TeacherRoleId field.
func (o *CreateTeacherEnrollmentByPlannedCourseIdRequest) SetTeacherRoleId(v int32) {
	o.TeacherRoleId = &v
}

func (o CreateTeacherEnrollmentByPlannedCourseIdRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateTeacherEnrollmentByPlannedCourseIdRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["teacher_id"] = o.TeacherId
	if !IsNil(o.TeacherRoleId) {
		toSerialize["teacher_role_id"] = o.TeacherRoleId
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CreateTeacherEnrollmentByPlannedCourseIdRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"teacher_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateTeacherEnrollmentByPlannedCourseIdRequest := _CreateTeacherEnrollmentByPlannedCourseIdRequest{}

	err = json.Unmarshal(data, &varCreateTeacherEnrollmentByPlannedCourseIdRequest)

	if err != nil {
		return err
	}

	*o = CreateTeacherEnrollmentByPlannedCourseIdRequest(varCreateTeacherEnrollmentByPlannedCourseIdRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "teacher_id")
		delete(additionalProperties, "teacher_role_id")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreateTeacherEnrollmentByPlannedCourseIdRequest struct {
	value *CreateTeacherEnrollmentByPlannedCourseIdRequest
	isSet bool
}

func (v NullableCreateTeacherEnrollmentByPlannedCourseIdRequest) Get() *CreateTeacherEnrollmentByPlannedCourseIdRequest {
	return v.value
}

func (v *NullableCreateTeacherEnrollmentByPlannedCourseIdRequest) Set(val *CreateTeacherEnrollmentByPlannedCourseIdRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateTeacherEnrollmentByPlannedCourseIdRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateTeacherEnrollmentByPlannedCourseIdRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateTeacherEnrollmentByPlannedCourseIdRequest(val *CreateTeacherEnrollmentByPlannedCourseIdRequest) *NullableCreateTeacherEnrollmentByPlannedCourseIdRequest {
	return &NullableCreateTeacherEnrollmentByPlannedCourseIdRequest{value: val, isSet: true}
}

func (v NullableCreateTeacherEnrollmentByPlannedCourseIdRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateTeacherEnrollmentByPlannedCourseIdRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


