/*
Eduframe - API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package eduframe

import (
	"encoding/json"
	"fmt"
)

// checks if the CustomAssociation type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CustomAssociation{}

// CustomAssociation struct for CustomAssociation
type CustomAssociation struct {
	// The unique identifier of the association.
	Id int32 `json:"id"`
	CustomObject CustomObject `json:"custom_object"`
	AdditionalProperties map[string]interface{}
}

type _CustomAssociation CustomAssociation

// NewCustomAssociation instantiates a new CustomAssociation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCustomAssociation(id int32, customObject CustomObject) *CustomAssociation {
	this := CustomAssociation{}
	this.Id = id
	this.CustomObject = customObject
	return &this
}

// NewCustomAssociationWithDefaults instantiates a new CustomAssociation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCustomAssociationWithDefaults() *CustomAssociation {
	this := CustomAssociation{}
	return &this
}

// GetId returns the Id field value
func (o *CustomAssociation) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *CustomAssociation) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *CustomAssociation) SetId(v int32) {
	o.Id = v
}

// GetCustomObject returns the CustomObject field value
func (o *CustomAssociation) GetCustomObject() CustomObject {
	if o == nil {
		var ret CustomObject
		return ret
	}

	return o.CustomObject
}

// GetCustomObjectOk returns a tuple with the CustomObject field value
// and a boolean to check if the value has been set.
func (o *CustomAssociation) GetCustomObjectOk() (*CustomObject, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CustomObject, true
}

// SetCustomObject sets field value
func (o *CustomAssociation) SetCustomObject(v CustomObject) {
	o.CustomObject = v
}

func (o CustomAssociation) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CustomAssociation) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["custom_object"] = o.CustomObject

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CustomAssociation) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"custom_object",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCustomAssociation := _CustomAssociation{}

	err = json.Unmarshal(data, &varCustomAssociation)

	if err != nil {
		return err
	}

	*o = CustomAssociation(varCustomAssociation)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "custom_object")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCustomAssociation struct {
	value *CustomAssociation
	isSet bool
}

func (v NullableCustomAssociation) Get() *CustomAssociation {
	return v.value
}

func (v *NullableCustomAssociation) Set(val *CustomAssociation) {
	v.value = val
	v.isSet = true
}

func (v NullableCustomAssociation) IsSet() bool {
	return v.isSet
}

func (v *NullableCustomAssociation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCustomAssociation(val *CustomAssociation) *NullableCustomAssociation {
	return &NullableCustomAssociation{value: val, isSet: true}
}

func (v NullableCustomAssociation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCustomAssociation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


