openapi: 3.0.3
info:
  title: Eduframe - API
  version: v1
servers:
- url: https://api.eduframe.nl/api/v1
security:
- Bearer: []
tags:
- description: ""
  name: accounts
- description: ""
  name: affiliations
- description: ""
  name: attendances
- description: ""
  name: authentications
- description: ""
  name: catalog-products
- description: ""
  name: catalog-variants
- description: ""
  name: categories
- description: ""
  name: comments
- description: ""
  name: course_locations
- description: ""
  name: course_tabs
- description: ""
  name: course_variants
- description: ""
  name: courses
- description: ""
  name: credit_categories
- description: ""
  name: credits
- description: ""
  name: custom_associations
- description: ""
  name: custom_field_options
- description: ""
  name: custom_objects
- description: ""
  name: custom_records
- description: ""
  name: discount_codes
- description: ""
  name: educators
- description: ""
  name: enrollments
- description: ""
  name: grades
- description: ""
  name: invoice_vats
- description: ""
  name: invoices
- description: ""
  name: labels
- description: ""
  name: leads
- description: ""
  name: material_groups
- description: ""
  name: materials
- description: ""
  name: meeting_locations
- description: ""
  name: meetings
- description: ""
  name: orders
- description: ""
  name: payment_methods
- description: ""
  name: payment_options
- description: ""
  name: payments
- description: ""
  name: planned_courses
- description: ""
  name: planning-conflicts
- description: ""
  name: planning-events
- description: ""
  name: planning-locations
- description: ""
  name: planning-materials
- description: ""
  name: planning-teachers
- description: ""
  name: program-blocks
- description: ""
  name: program-editions
- description: ""
  name: program-elements
- description: ""
  name: program-enrollments
- description: ""
  name: program-personal-program-elements
- description: ""
  name: program-programs
- description: ""
  name: referrals
- description: ""
  name: signup_questions
- description: ""
  name: tasks
- description: ""
  name: teacher_enrollments
- description: ""
  name: teacher_roles
- description: ""
  name: teachers
- description: ""
  name: theses
- description: ""
  name: users
- description: ""
  name: webhook-notifications
- description: |2

    <h4 id="label-Setup">Setup<span><a href="#label-Setup">&para;</a> <a href="#top">&uarr;</a></span></h4>

    <p>To setup a webhook, you can create one through the API or go to the admin setting to use the UI.</p>

    <h4 id="label-Webhook+Return+Payload">Webhook Return Payload<span><a href="#label-Webhook+Return+Payload">&para;</a> <a href="#top">&uarr;</a></span></h4>

    <p>An example payload for approving an order would look something like this:</p>

    <pre>{
      &quot;tenant_id&quot;: &quot;uuid&quot;                 // UUID of the tenant
      &quot;educator&quot;: &quot;some-subdomain&quot;,       // Subdomain of the educator
      &quot;event&quot;: &quot;account.updated&quot;          // Event that triggered the webhook
      &quot;event_data&quot;: &quot;Account&quot;,            // Event-specific data
    }</pre>

    <p>The Open API format of these payloads:</p>

    <pre class="ruby">{
      <span class="ruby-value">&quot;tenant_id&quot;:</span> {
        <span class="ruby-value">&quot;type&quot;:</span> <span class="ruby-string">&quot;string&quot;</span>
      },
      <span class="ruby-value">&quot;educator&quot;:</span> {
        <span class="ruby-value">&quot;type&quot;:</span> <span class="ruby-string">&quot;string&quot;</span>
      },
      <span class="ruby-value">&quot;event&quot;:</span> {
        <span class="ruby-value">&quot;type&quot;:</span> <span class="ruby-string">&quot;string&quot;</span>
      },
      <span class="ruby-value">&quot;event_data&quot;:</span> {
        <span class="ruby-value">&quot;type&quot;:</span> <span class="ruby-string">&quot;object&quot;</span>
      }
    }
    </pre>
  name: webhooks
paths:
  /accounts:
    get:
      operationId: get_accounts
      security:
      - Bearer:
        - relations:read
      summary: Get all accounts
      tags:
      - accounts
    post:
      operationId: create_account
      security:
      - Bearer:
        - relations:modify
      summary: Create an account
      tags:
      - accounts
  /accounts/{id}:
    get:
      operationId: get_account_by_id
      security:
      - Bearer:
        - relations:read
      summary: Get a single account
      tags:
      - accounts
    patch:
      operationId: update_account
      security:
      - Bearer:
        - relations:modify
      summary: Update an account
      tags:
      - accounts
  /affiliations:
    get:
      operationId: get_affiliations
      security:
      - Bearer:
        - relations:read
      summary: Get all affiliations
      tags:
      - affiliations
    post:
      operationId: create_affiliation
      security:
      - Bearer:
        - relations:modify
      summary: Create an affiliation affiliations
      tags:
      - affiliations
  /affiliations/{id}:
    delete:
      operationId: delete_affiliation_by_id
      security:
      - Bearer:
        - relations:destroy
      summary: Delete an affiliation
      tags:
      - affiliations
    patch:
      operationId: update_affiliation_by_id
      security:
      - Bearer:
        - relations:modify
      summary: Update an affiliation.
      tags:
      - affiliations
  /attendances:
    get:
      operationId: get_attendances
      security:
      - Bearer:
        - courses:read
      summary: Get all attendance records
      tags:
      - attendances
  /attendances/upsert:
    post:
      operationId: set_attendance
      security:
      - Bearer:
        - courses:modify
      summary: Set an attendance.
      tags:
      - attendances
  /authentications:
    post:
      operationId: create_authentication
      security:
      - Bearer:
        - authentications:modify
      summary: Create an authentication.
      tags:
      - authentications
  /catalog/products:
    get:
      operationId: get_catalog_products
      security:
      - Bearer:
        - courses:read
      summary: Get all catalog products
      tags:
      - catalog-products
  /catalog/products/{id}:
    get:
      operationId: get_catalog_product_by_id
      security:
      - Bearer:
        - courses:read
      summary: Get a catalog product record
      tags:
      - catalog-products
    patch:
      operationId: update_catalog_product_by_id
      security:
      - Bearer:
        - courses:modify
      summary: Update a catalog product
      tags:
      - catalog-products
  /catalog/variants:
    get:
      operationId: get_catalog_variants
      security:
      - Bearer:
        - courses:read
      summary: Get all catalog variants
      tags:
      - catalog-variants
  /catalog/variants/{id}:
    get:
      operationId: get_catalog_variant_by_id
      security:
      - Bearer:
        - courses:read
      summary: Get a catalog variant record
      tags:
      - catalog-variants
    patch:
      operationId: update_catalog_variant_by_id
      security:
      - Bearer:
        - courses:modify
        - courses:read
      summary: Update a catalog variant
      tags:
      - catalog-variants
  /categories:
    get:
      operationId: get_categories
      security:
      - Bearer:
        - courses:read
      summary: Get all category records
      tags:
      - categories
    post:
      operationId: create_category
      security:
      - Bearer:
        - courses:modify
      summary: Create a category.
      tags:
      - categories
  /categories/{id}:
    get:
      operationId: get_category_by_id
      security:
      - Bearer:
        - courses:read
      summary: Get a category record
      tags:
      - categories
    patch:
      operationId: update_category_by_id
      security:
      - Bearer:
        - courses:modify
      summary: Update a category.
      tags:
      - categories
  /comments:
    post:
      operationId: create_comment
      security:
      - Bearer: []
      summary: Create a comment.
      tags:
      - comments
  /comments/{id}:
    delete:
      operationId: delete_comment_by_id
      security:
      - Bearer: []
      summary: Delete a comment.
      tags:
      - comments
    patch:
      operationId: update_comment_by_id
      security:
      - Bearer: []
      summary: Update a comment.
      tags:
      - comments
  /course_locations:
    get:
      operationId: get_course_locations
      security:
      - Bearer:
        - settings:read
      summary: Get all course location records
      tags:
      - course_locations
    post:
      operationId: create_course_location
      security:
      - Bearer:
        - settings:modify
      summary: Create a course location.
      tags:
      - course_locations
  /course_locations/{id}:
    delete:
      operationId: delete_course_location_by_id
      security:
      - Bearer:
        - destroyable_settings:destroy
      summary: Delete a course location.
      tags:
      - course_locations
    get:
      operationId: get_course_location_by_id
      security:
      - Bearer:
        - settings:read
      summary: Get a course location record
      tags:
      - course_locations
    patch:
      operationId: update_course_location_by_id
      security:
      - Bearer:
        - settings:modify
      summary: Update a course location.
      tags:
      - course_locations
  /course_tabs:
    get:
      operationId: get_course_tabs
      security:
      - Bearer: []
      summary: Get all course tab records
      tags:
      - course_tabs
  /course_variants:
    get:
      operationId: get_course_variants
      security:
      - Bearer:
        - settings:read
      summary: Get all course variant records
      tags:
      - course_variants
    post:
      operationId: create_course_variant
      security:
      - Bearer:
        - settings:modify
        - settings:read
      summary: Create a course variant
      tags:
      - course_variants
  /course_variants/{id}:
    get:
      operationId: get_course_variant_by_id
      security:
      - Bearer:
        - settings:read
      summary: Get a course variant record
      tags:
      - course_variants
  /courses:
    get:
      operationId: get_courses
      security:
      - Bearer:
        - courses:read
      summary: Get all course records
      tags:
      - courses
    post:
      operationId: create_course
      security:
      - Bearer:
        - courses:modify
        - courses:read
      summary: Create a course.
      tags:
      - courses
  /courses/{id}:
    get:
      operationId: get_course_by_id
      security:
      - Bearer:
        - courses:read
      summary: Get a course record
      tags:
      - courses
    patch:
      operationId: update_course_by_id
      security:
      - Bearer:
        - courses:modify
        - courses:read
      summary: Update a course.
      tags:
      - courses
  /courses/{course_id}/planned_courses:
    get:
      operationId: get_planned_courses_by_course_id
      security:
      - Bearer:
        - courses:read
      summary: Get all planned course records of a single course
      tags:
      - planned_courses
  /courses/{course_id}/planned_courses/{id}:
    get:
      operationId: get_planned_courses_by_id_and_course_id
      security:
      - Bearer:
        - courses:read
      summary: Get a planned course record of a single course
      tags:
      - planned_courses
  /credit_categories:
    get:
      operationId: get_credit_categories
      security:
      - Bearer:
        - settings:read
      summary: Get all credit category records
      tags:
      - credit_categories
  /credits:
    get:
      operationId: get_credits
      security:
      - Bearer:
        - settings:read
      summary: Get all credit records
      tags:
      - credits
  /custom/{object_type}/associations:
    get:
      description: |
        ![Custom Objects](https://img.shields.io/badge/Feature-Custom_objects-1d8127)
      operationId: get_associations_of_object
      security:
      - Bearer:
        - settings:read
      summary: Get all associations of an system object
      tags:
      - custom_associations
      x-badges:
      - name: Beta
        color: '#7d15a3'
        position: after
  /custom/{object_type}/fields/{field_slug}/options:
    get:
      operationId: get_options_of_custom_field
      security:
      - Bearer:
        - settings:read
      summary: Get all options of a custom field
      tags:
      - custom_field_options
      x-badges:
      - name: Beta
        color: '#7d15a3'
        position: after
    post:
      operationId: add_option_to_custom_field
      security:
      - Bearer:
        - settings:modify
      summary: Add an option to a custom field
      tags:
      - custom_field_options
      x-badges:
      - name: Beta
        color: '#7d15a3'
        position: after
  /custom/{object_type}/fields/{field_slug}/options/{option_id}:
    delete:
      operationId: delete_option_of_custom_field
      security:
      - Bearer:
        - settings:modify
      summary: Delete an option from custom field
      tags:
      - custom_field_options
      x-badges:
      - name: Beta
        color: '#7d15a3'
        position: after
    get:
      operationId: get_option_of_custom_field
      security:
      - Bearer:
        - settings:read
      summary: Get an option of a custom field
      tags:
      - custom_field_options
      x-badges:
      - name: Beta
        color: '#7d15a3'
        position: after
    patch:
      operationId: update_option_of_custom_field
      security:
      - Bearer:
        - settings:modify
      summary: Update an option of a custom field
      tags:
      - custom_field_options
      x-badges:
      - name: Beta
        color: '#7d15a3'
        position: after
  /custom/objects:
    get:
      description: |
        ![Custom Objects](https://img.shields.io/badge/Feature-Custom_objects-1d8127)
      operationId: get_custom_objects
      security:
      - Bearer:
        - settings:read
      summary: Get all custom objects
      tags:
      - custom_objects
      x-badges:
      - name: Beta
        color: '#7d15a3'
        position: after
  /custom/objects/{object_id}:
    get:
      description: |
        ![Custom Objects](https://img.shields.io/badge/Feature-Custom_objects-1d8127)
      operationId: get_custom_object_by_object_id
      security:
      - Bearer:
        - settings:read
      summary: Get a custom object by object_id
      tags:
      - custom_objects
      x-badges:
      - name: Beta
        color: '#7d15a3'
        position: after
  /custom/objects/{object_id}/records:
    get:
      description: |
        ![Custom Objects](https://img.shields.io/badge/Feature-Custom_objects-1d8127)
      operationId: get_custom_records
      security:
      - Bearer:
        - settings:read
      summary: Get all custom records
      tags:
      - custom_records
      x-badges:
      - name: Beta
        color: '#7d15a3'
        position: after
    post:
      description: |
        ![Custom Objects](https://img.shields.io/badge/Feature-Custom_objects-1d8127)
      operationId: create_custom_record
      security:
      - Bearer:
        - settings:modify
      summary: Create a custom record
      tags:
      - custom_records
      x-badges:
      - name: Beta
        color: '#7d15a3'
        position: after
  /custom/objects/{object_id}/records/{record_id}:
    delete:
      description: |
        ![Custom Objects](https://img.shields.io/badge/Feature-Custom_objects-1d8127)
      operationId: delete_custom_record
      security:
      - Bearer:
        - destroyable_settings:destroy
      summary: Delete a custom record
      tags:
      - custom_records
      x-badges:
      - name: Beta
        color: '#7d15a3'
        position: after
    get:
      description: |
        ![Custom Objects](https://img.shields.io/badge/Feature-Custom_objects-1d8127)
      operationId: get_custom_record
      security:
      - Bearer:
        - settings:read
      summary: Get a custom record
      tags:
      - custom_records
      x-badges:
      - name: Beta
        color: '#7d15a3'
        position: after
    patch:
      description: |
        ![Custom Objects](https://img.shields.io/badge/Feature-Custom_objects-1d8127)
      operationId: update_custom_record
      security:
      - Bearer:
        - settings:modify
      summary: Update a custom record
      tags:
      - custom_records
      x-badges:
      - name: Beta
        color: '#7d15a3'
        position: after
  /customers/{id}: {}
  /discount_codes:
    get:
      operationId: get_discount_codes
      security:
      - Bearer:
        - orders:read
      summary: Get all discount codes
      tags:
      - discount_codes
  /educators/current:
    get:
      operationId: get_current_educator
      security:
      - Bearer: []
      summary: Get an educator record
      tags:
      - educators
  /enrollments:
    get:
      operationId: get_enrollments
      security:
      - Bearer:
        - orders:read
      summary: Get all enrollment records
      tags:
      - enrollments
  /enrollments/{id}:
    get:
      operationId: get_enrollment_by_id
      security:
      - Bearer:
        - orders:read
      summary: Get an enrollment record
      tags:
      - enrollments
    patch:
      operationId: update_enrollment_by_id
      security:
      - Bearer:
        - orders:read
        - orders:modify
      summary: Update an enrollment
      tags:
      - enrollments
  /enrollments/{id}/cancel:
    put:
      operationId: cancel_enrollment_by_id
      security:
      - Bearer:
        - orders:read
        - orders:modify
      summary: Cancel an enrollment
      tags:
      - enrollments
  /grades:
    post:
      operationId: create_grade
      security:
      - Bearer:
        - orders:modify
      summary: Create a grade
      tags:
      - grades
  /grades/{id}:
    delete:
      operationId: delete_grade_by_id
      security:
      - Bearer:
        - orders:destroy
      summary: Delete a grade.
      tags:
      - grades
    get:
      operationId: get_grade_by_id
      security:
      - Bearer:
        - orders:read
      summary: Get a grade record
      tags:
      - grades
    patch:
      operationId: update_grade_by_id
      security:
      - Bearer:
        - orders:modify
      summary: Update a grade
      tags:
      - grades
  /invoice_vats:
    get:
      operationId: get_invoice_vats
      security:
      - Bearer:
        - settings:read
      summary: Get all invoice vat records
      tags:
      - invoice_vats
    post:
      operationId: create_invoice_vat
      security:
      - Bearer:
        - settings:modify
      summary: Create an invoice vat.
      tags:
      - invoice_vats
  /invoices:
    get:
      operationId: get_invoices
      security:
      - Bearer:
        - invoices:read
      summary: Get all invoice records
      tags:
      - invoices
    post:
      operationId: create_invoice
      security:
      - Bearer:
        - invoices:read
        - invoices:modify
      summary: Create an invoice.
      tags:
      - invoices
  /invoices/{id}:
    get:
      operationId: get_invoice_by_id
      security:
      - Bearer:
        - invoices:read
      summary: Get an invoice record
      tags:
      - invoices
  /invoices/{id}/open:
    post:
      operationId: open_invoice_by_id
      security:
      - Bearer:
        - invoices:read
        - invoices:modify
      summary: |
        Changes the state from concept to open.
        This will assign the actual invoice number so it's ready for sending.
        If the current state is not concept, this endpoint does nothing.
      tags:
      - invoices
  /invoices/{id}/pdf:
    get:
      operationId: get_invoice_pdf_by_id
      security:
      - Bearer:
        - invoices:read
      summary: Get the base64 encoded version of the invoice PDF
      tags:
      - invoices
  /invoices/{invoice_id}/invoice_items: {}
  /invoices/{invoice_id}/payments:
    get:
      operationId: get_invoice_payments_by_invoice_id
      security:
      - Bearer:
        - payments:read
      summary: Get all payment records of an invoice
      tags:
      - payments
    post:
      operationId: create_invoice_payment_by_invoice_id
      security:
      - Bearer:
        - payments:modify
      summary: Create a payment.
      tags:
      - payments
  /invoices/{invoice_id}/payments/{id}:
    delete:
      operationId: delete_invoice_payment_by_id_and_invoice_id
      security:
      - Bearer:
        - destroyable_payments:destroy
      summary: Delete a payment.
      tags:
      - payments
  /labels:
    get:
      operationId: get_labels
      security:
      - Bearer:
        - settings:read
      summary: Get all labels
      tags:
      - labels
    post:
      operationId: create_label
      security:
      - Bearer:
        - settings:modify
      summary: Create a label
      tags:
      - labels
  /labels/{id}:
    delete:
      operationId: delete_label_by_id
      security:
      - Bearer:
        - destroyable_settings:destroy
      summary: Delete a label
      tags:
      - labels
    get:
      operationId: get_label_by_id
      security:
      - Bearer:
        - settings:read
      summary: Get a label
      tags:
      - labels
    patch:
      operationId: update_label_by_id
      security:
      - Bearer:
        - settings:modify
      summary: Update a label
      tags:
      - labels
  /leads:
    get:
      operationId: get_leads
      security:
      - Bearer:
        - leads:read
      summary: Get all lead records
      tags:
      - leads
    post:
      operationId: create_lead
      security:
      - Bearer:
        - leads:modify
      summary: Create a lead.
      tags:
      - leads
  /leads/{id}:
    delete:
      operationId: delete_lead_by_id
      security:
      - Bearer:
        - leads:destroy
      summary: Delete a lead.
      tags:
      - leads
    get:
      operationId: get_lead_by_id
      security:
      - Bearer:
        - leads:read
      summary: Get one lead record
      tags:
      - leads
  /material_groups:
    get:
      operationId: get_material_groups
      security:
      - Bearer:
        - settings:read
      summary: Get all material group records
      tags:
      - material_groups
    post:
      operationId: create_material_group
      security:
      - Bearer:
        - settings:modify
      summary: Create a material group.
      tags:
      - material_groups
  /material_groups/{id}:
    delete:
      operationId: delete_material_group_by_id
      security:
      - Bearer:
        - destroyable_settings:destroy
      summary: Delete a material group.
      tags:
      - material_groups
    get:
      operationId: get_material_group_by_id
      security:
      - Bearer:
        - settings:read
      summary: Get a material group record
      tags:
      - material_groups
    patch:
      operationId: update_material_group_by_id
      security:
      - Bearer:
        - settings:modify
      summary: Update a material group.
      tags:
      - material_groups
  /materials:
    get:
      operationId: get_materials
      security:
      - Bearer:
        - settings:read
      summary: Get all material records
      tags:
      - materials
    post:
      operationId: create_material
      security:
      - Bearer:
        - settings:modify
      summary: Create a material.
      tags:
      - materials
  /materials/{id}:
    delete:
      operationId: delete_material_by_id
      security:
      - Bearer:
        - destroyable_settings:destroy
      summary: Delete a material.
      tags:
      - materials
    patch:
      operationId: update_material_by_id
      security:
      - Bearer:
        - settings:modify
      summary: Update a material.
      tags:
      - materials
  /meeting_locations:
    get:
      operationId: get_meeting_locations
      security:
      - Bearer:
        - settings:read
      summary: Get all meeting location records
      tags:
      - meeting_locations
    post:
      operationId: create_meeting_location
      security:
      - Bearer:
        - settings:modify
      summary: Create a meeting location.
      tags:
      - meeting_locations
  /meeting_locations/{id}:
    delete:
      operationId: delete_meeting_location_by_id
      security:
      - Bearer:
        - destroyable_settings:destroy
      summary: Delete a course location.
      tags:
      - meeting_locations
    get:
      operationId: get_meeting_location_by_id
      security:
      - Bearer:
        - settings:read
      summary: Get an meeting location
      tags:
      - meeting_locations
    patch:
      operationId: update_meeting_location_by_id
      security:
      - Bearer:
        - settings:modify
      summary: Update a meeting location.
      tags:
      - meeting_locations
  /meetings:
    get:
      operationId: get_meetings
      security:
      - Bearer:
        - courses:read
      summary: Get all meeting records
      tags:
      - meetings
  /meetings/{id}:
    delete:
      operationId: delete_meeting_by_id
      security:
      - Bearer:
        - courses:destroy
      summary: Delete a meeting.
      tags:
      - meetings
    get:
      operationId: get_meeting_by_id
      security:
      - Bearer:
        - courses:read
      summary: Get an meeting record
      tags:
      - meetings
  /meetings/{id}/materials:
    get:
      operationId: get_planning_materials_of_meeting
      security:
      - Bearer:
        - courses:read
      summary: Get all planning materials of a meeting
      tags:
      - planning-materials
  /orders:
    get:
      operationId: get_orders
      security:
      - Bearer:
        - orders:read
      summary: Get all order records
      tags:
      - orders
    post:
      operationId: create_order
      security:
      - Bearer:
        - orders:modify
      summary: Create an order.
      tags:
      - orders
  /orders/{id}:
    get:
      operationId: get_order_by_id
      security:
      - Bearer:
        - orders:read
      summary: Get an order record
      tags:
      - orders
  /orders/{id}/approve:
    put:
      operationId: approve_order_by_id
      security:
      - Bearer:
        - orders:read
        - orders:modify
      summary: Approve an order
      tags:
      - orders
  /orders/{id}/cancel:
    put:
      operationId: cancel_order_by_id
      security:
      - Bearer:
        - orders:read
        - orders:modify
      summary: Cancel an order
      tags:
      - orders
  /orders/{id}/deny:
    put:
      operationId: deny_order_by_id
      security:
      - Bearer:
        - orders:read
        - orders:modify
      summary: Deny an order
      tags:
      - orders
  /orders/{id}/labels:
    post:
      operationId: add_label_to_order
      security:
      - Bearer:
        - orders:modify
      summary: Add label to an order
      tags:
      - labels
  /payment_methods:
    get:
      operationId: get_payment_methods
      security:
      - Bearer:
        - settings:read
      summary: Get all payment method records available for customers
      tags:
      - payment_methods
  /payment_options:
    get:
      operationId: get_payment_options
      security:
      - Bearer:
        - settings:read
      summary: Get all payment option records
      tags:
      - payment_options
  /payments/{id}:
    get:
      operationId: get_payment_by_id
      security:
      - Bearer:
        - payments:read
      summary: Get one payment record
      tags:
      - payments
  /planned_courses:
    get:
      operationId: get_planned_courses
      security:
      - Bearer:
        - courses:read
      summary: Get all planned course records
      tags:
      - planned_courses
    post:
      operationId: create_planned_course
      security:
      - Bearer:
        - courses:modify
      summary: Create a planned course.
      tags:
      - planned_courses
  /planned_courses/{id}:
    get:
      operationId: get_planned_course_by_id
      security:
      - Bearer:
        - courses:read
      summary: Get a planned course record
      tags:
      - planned_courses
    patch:
      operationId: update_planned_course_by_id
      security:
      - Bearer:
        - courses:modify
      summary: Update a planned course.
      tags:
      - planned_courses
  /planned_courses/{id}/cancel:
    put:
      operationId: cancel_planned_course_by_id
      security:
      - Bearer:
        - courses:destroy
      summary: Cancel a planned course.
      tags:
      - planned_courses
  /planned_courses/{planned_course_id}/meetings:
    get:
      operationId: get_meetings_by_planned_course_id
      security:
      - Bearer:
        - courses:read
      summary: Get all meeting records of a planned course
      tags:
      - meetings
  /planned_courses/{planned_course_id}/teacher_enrollments:
    get:
      operationId: get_teacher_enrollments_by_planned_course_id
      security:
      - Bearer:
        - courses:read
      summary: Get all teacher enrollments for given planned course.
      tags:
      - teacher_enrollments
    post:
      operationId: create_teacher_enrollment_by_planned_course_id
      security:
      - Bearer:
        - courses:modify
      summary: Enroll a teacher to the given planned course.
      tags:
      - teacher_enrollments
  /planning/conflicts:
    get:
      operationId: get_planning_conflicts
      security:
      - Bearer:
        - courses:read
      summary: Get all conflicts
      tags:
      - planning-conflicts
  /planning/events:
    get:
      operationId: get_planning_events
      security:
      - Bearer:
        - courses:read
      summary: Get all planning event records
      tags:
      - planning-events
  /planning/events/{id}:
    delete:
      operationId: delete_planning_event_by_id
      security:
      - Bearer:
        - courses:destroy
      summary: Delete a planning event.
      tags:
      - planning-events
    get:
      operationId: get_planning_event_by_id
      security:
      - Bearer:
        - courses:read
      summary: Get an planning event record
      tags:
      - planning-events
  /planning/events/{id}/materials:
    get:
      operationId: get_planning_materials_of_planing_event
      security:
      - Bearer:
        - courses:read
        - settings:read
      summary: Get all planning materials of a planning event
      tags:
      - planning-materials
  /planning/locations:
    get:
      operationId: get_planning_locations
      security:
      - Bearer:
        - settings:read
      summary: Get all locations that are available
      tags:
      - planning-locations
  /planning/materials:
    get:
      operationId: get_planning_materials
      security:
      - Bearer:
        - settings:read
      summary: Get all materials that are available
      tags:
      - planning-materials
  /planning/teachers:
    get:
      operationId: get_planning_teachers
      security:
      - Bearer:
        - relations:read
      summary: Get all teachers that are available
      tags:
      - planning-teachers
  /plugins/data/{id}: {}
  /plugins/plugins/{id}: {}
  /program/editions:
    get:
      description: |
        ![Program](https://img.shields.io/badge/Feature-Programs-1d8127)
      operationId: get_program_editions
      security:
      - Bearer:
        - courses:read
      summary: Get all program editions
      tags:
      - program-editions
    post:
      description: |
        ![Program](https://img.shields.io/badge/Feature-Programs-1d8127)
      operationId: create_program_edition
      security:
      - Bearer:
        - courses:modify
      summary: Create a program edition
      tags:
      - program-editions
  /program/editions/{id}:
    delete:
      description: |
        ![Program](https://img.shields.io/badge/Feature-Programs-1d8127)
      operationId: delete_program_edition_by_id
      security:
      - Bearer:
        - courses:destroy
      summary: Delete a program edition
      tags:
      - program-editions
    get:
      description: |
        ![Program](https://img.shields.io/badge/Feature-Programs-1d8127)
      operationId: get_program_edition_by_id
      security:
      - Bearer:
        - courses:read
      summary: Get a program edition
      tags:
      - program-editions
    patch:
      description: |
        ![Program](https://img.shields.io/badge/Feature-Programs-1d8127)
      operationId: update_program_edition_by_id
      security:
      - Bearer:
        - courses:modify
      summary: Update a program edition
      tags:
      - program-editions
  /program/editions/{id}/elements:
    get:
      description: |
        ![Program](https://img.shields.io/badge/Feature-Programs-1d8127)
      operationId: get_elements_of_program_edition
      security:
      - Bearer:
        - courses:read
      summary: Get the elements of a program edition
      tags:
      - program-editions
      x-badges:
      - name: Beta
        color: '#7d15a3'
        position: after
  /program/elements:
    get:
      description: |
        ![Program](https://img.shields.io/badge/Feature-Programs-1d8127)

        This endpoint will only return elements of type 'Course Element' that are directly linked to the program edition(s). It does not consider possible blocks.
      operationId: get_program_elements
      security:
      - Bearer:
        - courses:read
      summary: Get all elements
      tags:
      - program-elements
    post:
      description: |
        ![Program](https://img.shields.io/badge/Feature-Programs-1d8127)

        This endpoint can only create elements of type 'Course Element' that are directly linked to the program edition(s). It does not consider possible blocks.
      operationId: create_program_element
      security:
      - Bearer:
        - courses:modify
      summary: Create a program element
      tags:
      - program-elements
  /program/elements/{id}:
    delete:
      description: |
        ![Program](https://img.shields.io/badge/Feature-Programs-1d8127)

        This endpoint can only remove elements of type 'Course Element' that are directly linked to the program edition(s). It does not consider possible blocks.
      operationId: delete_program_element_by_id
      security:
      - Bearer:
        - courses:destroy
      summary: Delete a element
      tags:
      - program-elements
    get:
      description: |
        ![Program](https://img.shields.io/badge/Feature-Programs-1d8127)

        This endpoint will only return elements of type 'Course Element' that are directly linked to the program edition(s). It does not consider possible blocks.
      operationId: get_program_element_by_id
      security:
      - Bearer:
        - courses:read
      summary: Get an element
      tags:
      - program-elements
    patch:
      description: |
        ![Program](https://img.shields.io/badge/Feature-Programs-1d8127)

        This endpoint can only change elements of type 'Course Element' that are directly linked to the program edition(s). It does not consider possible blocks.
      operationId: update_program_element_by_id
      security:
      - Bearer:
        - courses:modify
      summary: Update an element
      tags:
      - program-elements
  /program/enrollments:
    get:
      description: |
        ![Program](https://img.shields.io/badge/Feature-Programs-1d8127)
      operationId: get_program_enrollments
      security:
      - Bearer:
        - courses:read
      summary: Get all program enrollments
      tags:
      - program-enrollments
  /program/enrollments/{id}:
    get:
      description: |
        ![Program](https://img.shields.io/badge/Feature-Programs-1d8127)
      operationId: get_program_enrollment_by_id
      security:
      - Bearer:
        - courses:read
      summary: Get a program enrollment record
      tags:
      - program-enrollments
  /program/enrollments/{id}/award_certificate:
    put:
      description: |
        ![Program](https://img.shields.io/badge/Feature-Programs-1d8127)
      operationId: award_certificate_to_program_enrollment_by_id
      security:
      - Bearer:
        - courses:read
        - courses:modify
      summary: Awards a certificate to a program enrollment
      tags:
      - program-enrollments
  /program/enrollments/{id}/cancel:
    put:
      description: |
        ![Program](https://img.shields.io/badge/Feature-Programs-1d8127)
      operationId: cancel_program_enrollment_by_id
      security:
      - Bearer:
        - courses:read
        - courses:modify
      summary: Cancel a program enrollment
      tags:
      - program-enrollments
  /program/enrollments/{id}/delete_certificate:
    post:
      description: |
        ![Program](https://img.shields.io/badge/Feature-Programs-1d8127)
      operationId: delete_certificate_from_program_enrollment_by_id
      security:
      - Bearer:
        - courses:read
        - courses:modify
      summary: Deletes a certificate from a program enrollment
      tags:
      - program-enrollments
  /program/programs:
    get:
      description: |
        ![Program](https://img.shields.io/badge/Feature-Programs-1d8127)
      operationId: get_programs
      security:
      - Bearer:
        - courses:read
      summary: Get all programs
      tags:
      - program-programs
    post:
      description: |
        ![Program](https://img.shields.io/badge/Feature-Programs-1d8127)
      operationId: create_program
      security:
      - Bearer:
        - courses:modify
      summary: Create a program
      tags:
      - program-programs
  /program/programs/{id}:
    delete:
      description: |
        ![Program](https://img.shields.io/badge/Feature-Programs-1d8127)
      operationId: delete_program_by_id
      security:
      - Bearer:
        - courses:destroy
      summary: Delete a program
      tags:
      - program-programs
    get:
      description: |
        ![Program](https://img.shields.io/badge/Feature-Programs-1d8127)
      operationId: get_program_by_id
      security:
      - Bearer:
        - courses:read
      summary: Get a program
      tags:
      - program-programs
    patch:
      description: |
        ![Program](https://img.shields.io/badge/Feature-Programs-1d8127)
      operationId: update_program_by_id
      security:
      - Bearer:
        - courses:modify
      summary: Update a program
      tags:
      - program-programs
  /referrals:
    get:
      operationId: get_referrals
      security:
      - Bearer:
        - settings:read
      summary: Get all referral records
      tags:
      - referrals
  /signup_questions:
    get:
      operationId: get_signup_questions
      security:
      - Bearer:
        - settings:read
      summary: Get all signup_question records
      tags:
      - signup_questions
  /tasks:
    get:
      operationId: get_tasks
      security:
      - Bearer: []
      summary: Get all task records
      tags:
      - tasks
    post:
      operationId: create_task
      security:
      - Bearer: []
      summary: Create a task.
      tags:
      - tasks
  /tasks/{id}:
    delete:
      operationId: delete_task_by_id
      security:
      - Bearer: []
      summary: Delete a task.
      tags:
      - tasks
    get:
      operationId: get_task_by_id
      security:
      - Bearer: []
      summary: Get a task record
      tags:
      - tasks
    patch:
      operationId: update_task_by_id
      security:
      - Bearer: []
      summary: Update a task.
      tags:
      - tasks
  /teacher_enrollments:
    get:
      operationId: get_teacher_enrollments
      security:
      - Bearer:
        - courses:read
      summary: Get all teacher enrollments.
      tags:
      - teacher_enrollments
    post:
      operationId: create_teacher_enrollment
      security:
      - Bearer:
        - courses:modify
      summary: Enroll a teacher to a planned_course.
      tags:
      - teacher_enrollments
  /teacher_enrollments/{id}:
    delete:
      operationId: delete_teacher_enrollment_by_id
      security:
      - Bearer:
        - courses:destroy
      summary: Delete a teacher enrollment.
      tags:
      - teacher_enrollments
    patch:
      operationId: update_teacher_enrollment_by_id
      security:
      - Bearer:
        - courses:modify
      summary: Update a teacher enrollment.
      tags:
      - teacher_enrollments
  /teacher_roles:
    get:
      operationId: get_teacher_roles
      security:
      - Bearer:
        - courses:read
      summary: Get all teacher roles
      tags:
      - teacher_roles
    post:
      operationId: create_teacher_role
      security:
      - Bearer:
        - courses:modify
      summary: Create a teacher role.
      tags:
      - teacher_roles
  /teacher_roles/{id}:
    delete:
      operationId: delete_teacher_role_by_id
      security:
      - Bearer:
        - courses:destroy
      summary: Delete a teacher role.
      tags:
      - teacher_roles
    get:
      operationId: get_teacher_role_by_id
      security:
      - Bearer:
        - courses:read
      summary: Get a teacher role
      tags:
      - teacher_roles
    patch:
      operationId: update_teacher_role_by_id
      security:
      - Bearer:
        - courses:modify
      summary: Update a teacher role.
      tags:
      - teacher_roles
  /teachers:
    get:
      operationId: get_teachers
      security:
      - Bearer:
        - teachers:read
      summary: Get all teacher records
      tags:
      - teachers
    post:
      operationId: create_teacher
      security:
      - Bearer:
        - teachers:modify
      summary: Create a new teacher
      tags:
      - teachers
  /teachers/{id}:
    get:
      operationId: get_teacher_by_id
      security:
      - Bearer:
        - teachers:read
      summary: Get a teacher record
      tags:
      - teachers
  /teachers/{id}/activate:
    post:
      operationId: activate_teacher_by_id
      security:
      - Bearer:
        - teachers:modify
      summary: Mark teacher as active
      tags:
      - teachers
  /teachers/{id}/deactivate:
    post:
      operationId: deactivate_teacher_by_id
      security:
      - Bearer:
        - teachers:modify
      summary: Mark teacher as inactive
      tags:
      - teachers
  /theses:
    get:
      description: |
        ![Program](https://img.shields.io/badge/Feature-Programs-1d8127)
      operationId: get_theses
      security:
      - Bearer:
        - courses:read
      summary: Get all thesis records
      tags:
      - theses
      x-badges:
      - name: Beta
        color: '#7d15a3'
        position: after
  /users:
    get:
      operationId: get_users
      security:
      - Bearer:
        - relations:read
      summary: Get all user records
      tags:
      - users
    post:
      operationId: create_user
      security:
      - Bearer:
        - relations:modify
      summary: Create a user.
      tags:
      - users
  /users/{id}:
    get:
      operationId: get_user_by_id
      security:
      - Bearer:
        - relations:read
      summary: Get an user record
      tags:
      - users
    patch:
      operationId: update_user_by_id
      security:
      - Bearer:
        - relations:modify
      summary: Update a user.
      tags:
      - users
  /users/{user_id}/authentications:
    get:
      operationId: get_authentications_by_user_id
      security:
      - Bearer:
        - authentications:read
      summary: Get the authentications of an user
      tags:
      - authentications
  /users/{user_id}/authentications/{id}:
    delete:
      operationId: delete_authentication_from_user
      security:
      - Bearer:
        - authentications:destroy
      summary: "Remove an authentication from a user. NOTE: It is impossible to remove\
        \ the last authentication for a user."
      tags:
      - authentications
  /webhooks:
    get:
      operationId: get_webhooks
      security:
      - Bearer:
        - settings:read
      summary: Get all registered webhooks
      tags:
      - webhooks
    post:
      operationId: create_webhook
      security:
      - Bearer:
        - settings:modify
      summary: Register a webhook.
      tags:
      - webhooks
  /webhooks/{id}:
    delete:
      operationId: delete_webhook_by_id
      security:
      - Bearer:
        - settings:modify
      summary: Delete a webhook.
      tags:
      - webhooks
    get:
      operationId: get_webhook_by_id
      security:
      - Bearer:
        - settings:read
      summary: Get a registered webhook
      tags:
      - webhooks
    patch:
      operationId: update_webhook_by_id
      security:
      - Bearer:
        - settings:modify
      summary: Update a webhook.
      tags:
      - webhooks
  /webhooks/{webhook_id}/notifications:
    get:
      operationId: get_webhook_notifications_by_webhook_id
      security:
      - Bearer:
        - settings:read
      summary: Get the notifications for a specific webhook
      tags:
      - webhook-notifications
  /webhooks/{webhook_id}/notifications/failed:
    get:
      operationId: get_webhook_notifications_failed
      security:
      - Bearer:
        - settings:read
      summary: Get the failed webhook notifications
      tags:
      - webhook-notifications
      x-badges:
      - name: Beta
        color: '#7d15a3'
        position: after
components:
  securitySchemes:
    Bearer:
      in: header
      name: Authorization
      type: apiKey
